softeer5th/Team2-Getit

- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/GetBuildingResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/entity/Building.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/FastestRouteResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/GetCautionResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/GetDangerResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/GetRiskRoutesResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/RouteDetailDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/RouteInfoDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
모든 DTO의 생성방식을 factory method 방식으로 통일하였고, 그로인해 영향받는 코드를 수정하였습니다.
> [UNI-63] chore : DTO 생성자를 builder 패턴에서 factory method 패턴으로 통일

- .github/release-drafter-config.yml
> chore: 릴리즈 노트 추가

- uniro_frontend/src/constant/enum/markerEnum.ts
- uniro_frontend/src/data/types/route.d.ts
1. RoutePoint Enum 중복 선언 제거 및 Import 수정
> [UNI-96] fix : RoutePoint Enum 중복 선언 제거

- uniro_frontend/src/components/loading/loading.tsx
1. Loading 컴포넌트 빌드 환경 사진 로딩 문제 해결
> [UNI-97] fix : Loading 컴포넌트 빌드 환경 사진 로딩 문제 해결

- uniro_backend/.gitignore
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/CorsConfig.java
- uniro_backend/src/main/resources/application-dev.yml
- uniro_backend/src/main/resources/application-local.yml
- uniro_backend/src/main/resources/application-test.yml
> [UNI-118] chore : CORS 설정 추가

- .github/workflows/fe-admin-deploy.yml
- uniro_frontend/src/App.tsx
- uniro_frontend/src/hooks/useRedirectUndefined.tsx
1. 랜딩 페이지, 데모 페이지 라우터 변경
랜딩 페이지 = "/"
데모 페이지 ="/demo"
> [UNI-121] chore : 서비스 라우터 변경

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/utils/GeoUtils.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeApi.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/service/NodeService.java
- 위도, 경도 순서가 바뀌어서 변경합니다.
- feat/
> [UNI-136] fix: 위도, 경도 수정

- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
모든 길 조회 중 코어노드가 없는 예외상황에서 응답이 가지 않는 상황을 해결하였습니다.
> [UNI-137] fix : 모든 길 조회 로직 수정

- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/repository/RouteRepository.java
native query의 대소문자 문제로 발생한 오류를 수정하였습니다.
> [UNI-134] fix : sql문 오류 해결 - 대소문자

- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/aspect/RevisionOperationAspect.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/entity/RevInfo.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/entity/RevisionOperationType.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteApi.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
1. 길 추가했을 때, audit 쪽에서 univId NotNull 오류가 생겼습니다. 해당 이벤트에 대한 audit 설정이 안돼서 발생한 문제였습니다. 이를 해결하기 위해 audit 과 관련된 어노테이션을 추가했습니다.
2. audit 쪽 시간을 보는데 불편함이 있어 long 였던 타입을 LocalDateTime 으로 변경했습니다.
3. 기존 `길 추가 API` 에서 위험&주의 요소가 null로 들어가지 않게 EmptySet 를 넣어줬습니다.
- feat/
> [UNI-135] fix: 길 추가 API 오류 수정

- uniro_frontend/src/pages/navigationResult.tsx
> [UNI-150] fix : 길찾기 캐시 저장 해제

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/constant/UniroConst.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/RouteDetailResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/RouteInfoResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
- 길 찾기 상세경로에서 주의요소 사유를 추가하였습니다.
- distance를 실제거리에 가깝게 산정하도록 로직을 수정하였습니다.
- 빌딩 노드와 연결된 route의 가중치를 1e8(1억) 으로 설정하였습니다.
- 길 찾기 도중 위험한 길은 추천하지 않도록 수정하였습니다.
- 휠체어 이동속도를 고려하여 가중치를 변경하였습니다.
- 길 찾기 경로 중 빌딩 노드를 거치는 경우 예외처리 하였습니다.
- 전체 changed files로 리뷰하시는 것보다 commit 단위로 리뷰하시는게 좋을 것 같습니다!
[UNI-160]: https://uniro.atlassian.net/browse/UNI-160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UNI-153]: https://uniro.atlassian.net/browse/UNI-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UNI-151]: https://uniro.atlassian.net/browse/UNI-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UNI-152]: https://uniro.atlassian.net/browse/UNI-152?atlOrigin=eyJpIjoiNWRkNT …
> [UNI-160] feat & refactor : 길찾기 로직에서 FE 요구사항 반영 및 건물노드 관련 로직 수정

- .github/workflows/be-ci.yml
- uniro_backend/build.gradle
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/entity/Node.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/CoreRoute.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/Route.java
- uniro_backend/src/main/resources/application-test.yml
- uniro_backend/src/test/java/com/softeer5/uniro_backend/UniroBackendApplicationTests.java
- uniro_backend/src/test/java/com/softeer5/uniro_backend/fixture/RouteFixture.java
- uniro_backend/src/test/java/com/softeer5/uniro_backend/route/RouteCalculationServiceTest.java
- ci/cd 동작에서 테스트 코드가 정상적으로 동작할 수 있도록 세팅했습니다.
- 로컬에서도 테스트가 성공하도록 구축했습니다.
- application-test.yml 파일을 확인하시면 됩니다!
- 테스트 환경 구축에 있어 아래와 같은 고민이 있었습니다. 제 결론은 테스트 컨테이너를 사용하기를 제안드리는 것입니다. 하지만 더 좋은 방법이나 로컬 db 사용이 더 좋을 것 같다고 판단되시면 편하게 말씀주세요!!!
<br>
- 저희 테스트환경의 데이터베이스에 대해 고민이 필요했습니다.
- 기존 h2 db의 경우에는 저희가 자주 사용하는 mysql geo 관련된 기능들이 h2에서는 호환이 잘 되지 않은 문제가 있었습니다.
- 이를 해결하기 위해 고민했던 방법은 `로컬 db` 와 [테스트 컨테이너](https://hogwart-scholars.tistory.com/entry/Spring-Boot-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BB%A8%ED%85%8C%EC%9D%B4%EB%84%88%EB%A1%9C-%ED%85%8C%EC%8A%A4%ED%8A%B8%ED%95%98%EA%B8%B0) 입니다.
<br>
- 테스트 컨테이너는 도커 컨테이너를 활용하여 외부 의존성들을 포함한 테스트 환경을 구축하고 관리하는 것을 간편하게 해주는 오픈 소스 java 라이브러리입니다.
- 장점1 : 개발자마다 동일한 로컬 db를 유지/관리할 필요가 없다는 장점이 있습니다. (h2 db와 비슷한 장점)
- 장점2 : 운영 환경과 거의 동일한 테스트 환경을 구축할 수 있다.
- 단점1 : 테스트 돌릴 때마다 테스트 …
> [UNI-138] 테스트 환경 복구 및 ci/cd 테스트 환경 구축

- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
- Route 쪽에서 불변리스트를 반환하는데 clear() 함수를 호출하여서 에러가 발생했습니다.
- 따라서 clear 가 아닌 새로운 empty list를 반환하도록 처리를 해뒀습니다.
- feat/
> [UNI-174] fix: 빠른 길 계산에서 불변 리스트 반환에 대한 오류 처리

- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
로직 누락으로 인하여 길 찾기 결과에서 정렬되지 않던 문제를 해결하였습니다.
> [UNI-159] fix : 길찾기 결과가 정렬되지 않던 문제 해결

- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/aspect/RevisionOperationAspect.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/entity/RevisionOperationType.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/utils/RouteUtils.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/request/CreateBuildingNodeReqDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/repository/BuildingRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteApi.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/request/CreateBuildingRouteReqDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/repository/RouteRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
- 빌딩 노드와 기존 노드를 연결시키는 방식으로 API를 구현하였습니다.
- 빌딩 노드와 연결된 간선은 모두 1e8의 가중치를 가집니다. (기존 노드와 차별화를 위한 작업)
- 빌딩 노드와 연결된 간선으로 인하여 모든 길 조회 로직에 변화가 생겨, 다음 PR과 함께 머지하겠습니다.
> [UNI-156] 빌딩과 연결된 간선 API 개발

- uniro_admin_frontend/src/api/route.ts
- uniro_admin_frontend/src/container/building/buildingAddContainer.tsx
1. Admin에서 빌딩 추가에 사용할 수 있는 건물 -> 길 연결 API를 선 반영했습니다.
2. 길 연결이 완료 되었다면, 초기화하는 로직을 넣었습니다.
https://github.com/user-attachments/assets/dd27c824-8891-4269-a318-ab5559a0c9b7
> [UNI-189] feat : 건물 -> 길 연결 API 반영

- uniro_frontend/src/api/route.ts
- uniro_frontend/src/hooks/useRoutePoint.ts
- uniro_frontend/src/pages/buildingSearch.tsx
> [UNI-190] feat : 건물 리스트 API 적용 및 Default 도착지 제거

- uniro_backend/src/main/java/com/softeer5/uniro_backend/external/MapClientImpl.java
google map API 최대 batch size를 조정하였습니다. (512 -> 100)
> [UNI-200] google map API 최대 batch size 조정

- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
- uniro_backend/src/test/java/com/softeer5/uniro_backend/route/RouteCalculationServiceTest.java
- 길 추가에서 셀프 크로스 오류를 해결했습니다.
- 해당 예외케이스들은 wiki 에 정리했습니다.
- 테스트 코드 참고
- feat/
> [UNI-133] fix: 길 추가에서 셀프 크로스 오류 해결

- uniro_frontend/src/pages/map.tsx
1.건물 마커 클릭시 지도가 건물 정 가운데로 오지 않는 문제를 해결했습니다.
```typescript
const moveToBound = () => {
if (selectedMarker?.type === Markers.BUILDING) {
buildingBoundary.current = new google.maps.LatLngBounds();
buildingBoundary.current.extend(new google.maps.LatLng(selectedMarker?.property?.lat as number, selectedMarker?.property?.lng as number));
// 라이브러리를 다양한 화면을 관찰해보았을 때, h-가 377인것을 확인했습니다.
map?.fitBounds(buildingBoundary.current, {
top: 0,
right: 0,
bottom: BOTTOM_SHEET_HEIGHT,
left: 0,
});
}
};
```
ref로 sheetHeight를 따라가려고 했으나, 만약 sheetHeight가 변경될때마다 fitBounds를 호출한다면 비효율적이라고 생각했습니다.
때문에 라이브러리를 관찰해본 결과, React Portal을 통해 생성된 bottom sheet는 모두 377px로 고정이었습니다.
--rsbs-overlay-h : 377px; 를 계속 다양한 화면에서 관찰해보았는데 모두 고정되어 우선 bottom padding을 377px로 고정해 bound를 만들어주었습니다.
만약 나중에 이전을 하게 된다면, window Height를 기준으로 bottom …
> [UNI-206] fix : 건물 마커 클릭시 지도가 건물 정 가운데로 오지 않는 문제 해결

- uniro_frontend/src/components/map/mapMarkers.tsx
- uniro_frontend/src/pages/map.tsx
- uniro_frontend/src/pages/reportRisk.tsx
1. 위험 주의 요소 여러개인 경우 애니메이션 추가
- 기존에는 위험 주의 요소가 한 개인 경우, 첫 번째 요소만 보여주던 문제를 해결하였습니다. 
-  백엔드 팀원들의 의견을 받아서 아래에서 위로 올라오는 글자 형태로 전환하였습니다.
- 아쉽게도 무한 루프를 도는 방법은 생각해내지 못해서 @jpark0506 준혁님께서 같이 고민해주시면 감사하겠습니다.
- 기존에 BottomSheet 등 다양한 애니메이션을 위해 설치한 라이브러리 framer-motion 라이브러리의 animate함수를 사용하였습니다. 
- [motion.dev](https://github.com/motiondivision/motion) 라이브러리에서 `animate` 함수로 Element, 와 애니메이션 옵션을 넣어 실행할 수 있습니다.
- 현재는 텍스트가 38px로 고정되어 고정 사이즈로 translate를 시킵니다.
```typescript
function createAnimatedTextElement(type: MarkerTypes, titles: string[]): HTMLElement {
const titleContainer = document.createElement("div");
const elements = [];
const _title = [...titles, titles[0]];
for (const title of _title) {
const factorTitle = document.createElement("p");
factorTitle.innerText = title;
factorTitle.className = …
```
> [UNI-212] feat : 위험 주의 마커 요소 여러개인 경우 애니메이션 추가

- uniro_frontend/src/component/NavgationMap.tsx
1.  건물과 길을 이어주는 길을 생성했습니다.
https://developers.google.com/maps/documentation/javascript/examples/overlay-symbol-dashed를 참고해 코드를 작성했습니다.
> [UNI-211] feat : 건물과 길을 이어주는 길 생성

- uniro_frontend/src/pages/reportForm.tsx
#️⃣ 작업 내용
1. 불편한 길 제보 페이지 오타 수정
- conflict solve 과정중에 잘못 지워진 것 같습니다. 더 주의해서 PR 올리겠습니다!
> [UNI-230] hotfix : 불편한 길 제보하기 코드 오타 수정

- uniro_frontend/src/api/nodes.ts
- uniro_frontend/src/api/search.ts
- uniro_frontend/src/api/transformer/nodes.ts
- uniro_frontend/src/api/type/response/nodes.d.ts
- uniro_frontend/src/components/customInput.tsx
- uniro_frontend/src/pages/buildingSearch.tsx
- uniro_frontend/src/pages/universitySearch.tsx
1. 한글 입력 state 관리 로직 적용
2. 학교리스트 검색 API 연결
3. 건물리스트 검색 API 연결
- onChange마다 API를 호출하게 될 경우, 불필요한 API 호출이 자주 일어나게 되어, 이를 처리하기 위해 Input에 debounce를 적용하였습니다.
```typescript
const timeOutRef = useRef<number>();
const resetInput = () => {
setValue('');
handleDebounce('');
};
const handleDebounce = (input: string) => {
if (timeOutRef.current) {
clearTimeout(timeOutRef.current);
}
timeOutRef.current = setTimeout(() => {
onChangeDebounce(input);
timeOutRef.current = undefined;
}, 300);
};
const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
const currentInput: string = e.target.value;
setValue(currentInput);
handleDebounce(currentInput);
};
```
- 300ms의 딜레이를 주어, 300ms 동안 입력이 존재하지 않을 경우, API를 호출하는 로직입니다.
- 기존에 이미 timeOut이 존재하다면 초기화하여, 300ms를 새로 Timeout 등록하였습니다.
| onChange  | onChangeDebounce …
> [UNI-77] feat : 한글 debounced 입력 구현 / 학교 검색, 건물 검색 API 연결

- uniro_frontend/src/App.tsx
- uniro_frontend/src/pages/buildingSearch.tsx
> [UNI-235] feat : 에러바운더리 key 부여

- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/dto/UnivInfo.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/entity/Univ.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivCustomRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivCustomRepositoryImpl.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/service/UnivService.java
- 대학교 관련 데이터를 추가했습니다.
- 추가목록은 아래와 같습니다.
- 대학교 중점 좌표
- 대학교 좌상단 좌표 (현재는 사용하지 않지만, 사용할 가능성이 있어서 추가)
- 대학교 우하단 좌표 (현재는 사용하지 않지만, 사용할 가능성이 있어서 추가)
- 대학교 영역 폴리곤
- feat/
> [UNI-244] feat: 학교마다 좌표 및 폴리곤 반환 기능 구현

- uniro_frontend/src/api/transformer/route.ts
- uniro_frontend/src/component/NavgationMap.tsx
- uniro_frontend/src/components/navigation/card/bottomCardList.tsx
- uniro_frontend/src/components/navigation/navBar/navigationNavBar.tsx
- uniro_frontend/src/components/navigation/navigationDescription.tsx
- uniro_frontend/src/pages/navigationResult.tsx
1. 주의 경로와 안전 경로가 동일할 시 안전 경로만 나오도록 수정
2. 도보, 휠체어, 전동휠체어 순으로 Sub Nav Bar 순서 변경
3. 도보 결과만 나올시, 휠체어, 전동휠체어 버튼 제거
4. 전동휠체어 소요시간 부분의 제목을 동적 제목으로 변경
5. 중점 위에 찍는 marker interpolate 하는 함수 생성
6. Animated value를 바텀 카드에 적용
WHEEL_FAST의 요청 중, hasCaution이 false가 요청되었을 때, 안전 경로인 경우의 수를 빼먹어, hasCaution을 조건문에 넣어, transformer를 보강했습니다.
```typescript
export const transformFastRoute = (data: GetFastestRouteResponse): NavigationRouteListRecordWithMetaData => {
// 나머지는 동일
case "WHEEL_FAST":
if (route.manualTotalCost && route.hasCaution) {
record[`MANUAL & CAUTION`] = {
hasCaution: route.hasCaution,
totalDistance: route.totalDistance,
totalCost: route.manualTotalCost ?? 0,
routes: route.routes,
routeDetails: route.routeDetails,
};
}
if (route.electricTotalCost && route.hasCaution) {
record[`ELECTRIC & CAUTION`] …
```
> [UNI-248] fix : 주의 경로와 안전 경로가 동일할 시 안전 경로만 나오도록 수정

- uniro_frontend/src/pages/map.tsx
bounds가 다른 요소들에 영향(marker, paths 등등) 받아, 우선 center만 조정하는 것으로 수정했습니다.
같이 정상 동작 확인했습니다.
같이 정상 동작 확인했습니다.
fe
> [UNI-276] hotfix : 대학 bounds 제거

- uniro_backend/Dockerfile
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/GlobalExceptionHandler.java
> [UNI-280] fix: oom 추적을 위한 추가

- uniro_frontend/src/pages/reportRisk.tsx
- uniro_frontend/src/pages/reportRoute.tsx
> [UNI-284] feat : 길 제보하기, 길 신고하기 초기 좌표 대학에 맞게 변경

- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/aspect/RevisionOperationAspect.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/setting/CustomReversionListener.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/setting/RevisionContext.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
- revInfo 관련 오류를 해결했습니다.
- feat/
> [UNI-285] fix: revinfo 오류 해결

- uniro_backend/Dockerfile
> [UNI-285] fix: 컨테이너 수정

- uniro_frontend/src/map/initializer/googleMapInitializer.ts
> [UNI-286] fitBounds의 원활한 이동을 위한 map minZoom Level 조정

- uniro_backend/build.gradle
- 모니터링에 불편함이 있어 프르메테우스와 그라파나 간단히 붙여봤습니다.
- feat/
> [UNI-289] feat: 프로메테우스 추가

- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
- 특정 버전에서 만든 것부터 롤백되는 문제를 해결했습니다.
- 추가로 동시성 문제를 해결하기 위해 임시방편으로 synchronized 방법을 사용했습니다.
- feat/
> [UNI-287] fix: 롤백 로직 오류 해결

- uniro_backend/src/main/java/com/softeer5/uniro_backend/building/entity/Building.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/building/repository/BuildingCustomRepositoryImpl.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/building/service/BuildingService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/entity/Univ.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivCustomRepositoryImpl.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/service/UnivService.java
- 음성인식 검색 기능을 구현했습니다.
- 검색 기능을 통일해도 좋을 것 같아서 검색에는 모두 trim된 이름만 받도록 FE와 협의했습니다.
- feat/
> [UNI-294] feat: 음성인식 검색 구현

- .github/workflows/fe-admin-deploy.yml
- .github/workflows/fe-deploy.yml
- uniro_admin_frontend/Dockerfile
- uniro_admin_frontend/src/App.tsx
- uniro_frontend/.gitignore
- uniro_frontend/Dockerfile
- uniro_frontend/src/App.tsx
```typescript
- name: Docker 이미지 빌드 및 푸시
uses: docker/build-push-action@v3
with:
context: .
file: uniro_frontend/Dockerfile
push: true
tags: gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
cache-from: type=gha
cache-to: type=gha,mode=max
```
```typescript
FROM node:22-alpine AS build
WORKDIR /app
COPY ./uniro_frontend/package*.json .
RUN --mount=type=cache,target=/root/.npm \
npm set cache /root/.npm && \
npm install
COPY ./uniro_frontend .
RUN npm run build
FROM nginx:alpine
COPY uniro_frontend/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
```
1차 빌드인 node는 slim->alpine 버전으로 변경하였습니다.
2차 배포 컨테이너 제작을, 일반 nginx 컨테이너에서 nginx:alpine으로 변경했습니다.
감사합니다
Cache를 저장하는 과정 때문에 초기 빌드 시간이 …
> [UNI-288] feat : github cache를 사용한 빌드 속도 개선

- .github/workflows/fe-admin-deploy.yml
- .github/workflows/fe-deploy.yml
기존에 배포시 nginx container를 열고 재시작했는데, 다시 nginx를 로드하도록 변경했습니다.
감사합니다.
-
fe
> [UNI-334] fix : FE Deploy code 수정

- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/AllRoutesInfo.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/repository/RouteRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
- SSE를 통한 길 조회 리턴타입에 batchSize를 추가하였습니다. (원활한 SSE 연결 종료를 위해)
> [UNI-330] feat : SSE 요청 시 batchSize를 함께 리턴하도록 구현

- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/FastestRouteResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/enums/DirectionType.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
- 도보에 위험요소가 포함될 경우 상세정보에 추가할 수 있도록 로직을 작성하였습니다.
> [UNI-344] fix : 도보에서는 위험요소도 반영되도록 변경

- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/RouteDetailResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
> [UNI-352] refactor : DangerFactor 누락 해결

- uniro_frontend/src/components/customInput.tsx
- uniro_frontend/src/pages/map.tsx
- uniro_frontend/src/pages/navigationResult.tsx
1. 마커 이미지 변경 오류 수정
2. 음성인식 제거
3. 네비게이션 결과 페이지 스크롤 수정
> [UNI-357] fix : QA 버그 수정

- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCacheCalculator.java
> [UNI-355] fix : 특정 버전 조회 오류 수정

- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCacheCalculator.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
특정 버전에서 빌딩노드가 리턴되지 않는 오류를 수정하였습니다.
> [UNI-355] fix : 특정 버전에서 빌딩 노드 수정

- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
- 길 찾기 상세에서 체크포인트 갱신이 안되던 상황 해결
> [UNI-351] fix : 길 찾기 상세에서 체크포인트 갱신이 안되던 상황 해결

- uniro_frontend/index.html
- uniro_frontend/public/robots.txt
SEO를 개선했습니다.
3가지 방식을 사용했는데,
1. meta tag
2. open graph tag
3. robots.txt 작성
1. description
```html
<meta name="description" content="UNIRO, 함께 밝히는 캠퍼스의 길. 대학생이 직접 만들어가는 참여형 배리어프리 맵에 참여해보세요." />
```
가장 중요한 meta tag로 아래 빨간 네모처럼 사이트를 설명하는 부분에 들어가도록 하는 태그입니다.
2. robots
```html
<meta name="robots" content="index, follow" />
```
검색 엔진이 이 페이지를 어떻게 크롤링할지 결정하는 태그입니다.
index로 이 페이지를 검색 엔진 색인에 추가하고, follow로 이 페이지 내의 링크를 따라가도록 허용 (즉, 다른 페이지도 크롤링 가능)
3. googlebot
```html
<meta name="googlebot" content="index, follow" />
```
구글 봇(Google 크롤러)이 2번과 동일한 역할을 하도록 하는 크롤러입니다.
4. google
```html
<meta name="google" content="notranslate" />
```
자동 번역 기능이 켜지지 않도록 합니다.
1. title, description, image -> SNS 공유시 기본적으로 보여지게 될 정보들
2. og:type (컨텐츠 유형) -> website 옵션으로 웹사이트임을 표시
3. og:url (페이지 URL) -> 대표로 접속할 url을 표시
4. …
> [UNI-282] SEO 개선하기

- uniro_frontend/index.html
본래 백엔드로부터 S3 링크를 받아서 올리려고 했지만, 직접적인 route를 올리는 것이 보안상 안전하지 않을 것으로 판단하여, nginx에서 static으로 호스팅 하도록 변경했습니다.
```nginx.conf
location /static/ {
root /var/www/uniro;
autoindex off;
expires 30d;
add_header Cache-Control "public, max-age=2592000, immutable";
}
location /og-image {
root /var/www/uniro/static;
rewrite ^/og-image$ /image.png break;
expires 30d;
add_header Cache-Control "public, max-age=2592000, immutable";
}
```
docker-compose.yml
```
container_name: nginx-container
volumes:
// 보안상 밝히지 않는 경로들..
- ./static:/var/www/uniro/static:ro
```
감사합니다.
https://www.uniro.site/og-image
fe
> [UNI-365] OG TAG image 추가

- uniro_backend/src/main/java/com/softeer5/uniro_backend/building/service/BuildingService.java
- 건물 노드 생성시 @NotNull 조건이 있어 생성되지 않은 오류 해결했습니다.
- feat/
> [UNI-355] fix: NotNull 문제 해결

- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/repository/RouteRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
- fetchSize = 1로 변경하여 stream하게 데이터를 전달받도록 변경
- https://dev.mysql.com/doc/connector-j/en/connector-j-reference-implementation-notes.html
- 응답용 fetchSize에 정상적인 값이 들어가도록 수정
> [UNI-329] stream 사이즈 변경 & 배치사이즈 응답 로직 수정

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/RedisConfig.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/external/redis/RedisService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
- 기존에 존재했던 로컬캐시는 관리의 복잡성으로 인해 삭제했습니다.
- batch size도 redis 에 저장하기 위해 StringRedisTemplate 를 사용했습니다.
- feat/
> [UNI-199] fix: 로컬캐시 오류 해결 및 batch size 저장 로직 수정

- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
- redis 키 충돌로 인한 문제 해결을 했습니다.
- feat/
> [UNI-199-v2] fix: key 충돌 해결

- .github/workflows/fe-admin-deploy.yml
- uniro_admin_frontend/src/AppRouter.tsx
- uniro_admin_frontend/src/api/route.ts
- uniro_admin_frontend/src/component/LogMap.tsx
- uniro_admin_frontend/src/page/buildingPage.tsx
- uniro_admin_frontend/src/page/simulationPage.tsx
Admin에서 발견된 버그들을 수정했습니다. 
감사합니다.
-
fe
> [HOTFIX] [FE] Admin QA Hotfix

- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/repository/RevInfoRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
> [UNI-115] feat : 학교마다 지정된 버전 미만으로는 조회되지 않도록 변경

- uniro_backend/Dockerfile
- Xms 500 설정을 통해 성능을 개선했습니다.
- feat/
> [UNI-186] refactor: Xms 500 설정

- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
길찾기 휴리스틱 중 고도 관련 데이터가 반대로 들어가는 현상을 수정하였습니다.
> [UNI-247] fix : 길 찾기 오류 수정
