- uniro_frontend/package-lock.json
- uniro_frontend/package.json
- uniro_frontend/src/App.tsx
- uniro_frontend/src/component/Map.tsx
- uniro_frontend/src/constant/bounds.ts
- uniro_frontend/src/constant/university.ts
- uniro_frontend/src/hooks/useMap.tsx
- uniro_frontend/src/map/initializer/googleMapInitializer.ts
- uniro_frontend/src/map/loader/googleMapLoader.ts
1. 지도 라이브러리 설치 (Loader, Google Map Type)
2. 초기 지도 컴포넌트 제작
- 우선 테스트 용으로 메인 화면에 500 * 500으로 넣어놨습니다.
3. 지도 관련 hook 생성 useMap
4. React Router 라이브러리 설치
- 미리 의존성이 들어가면 좋을 것 같아 설치했습니다.
> 지도 객체들의 type중에 null이 많이 있는데, 그 부분 괜찮은지 봐주시면 좋을 것 같습니다.
> 지도 Hook을 Provider로 바꿔야할지 고민이긴 한데, 차차 이야기해보면 좋을 것 같습니다.
> [UNI-38] feat: 초기 지도 컴포넌트 및 훅 생성

- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeApi.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/BuildingNode.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/GetBuildingResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/entity/Building.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/repository/BuildingRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/service/NodeService.java
- uniro_backend/src/main/resources/application-local.yml
- uniro_backend/src/main/resources/data.sql
- 건물 노드 조회하는 API 구현했습니다.
- `level` , `좌상단 좌표` , `우하단 좌표` 를 통해서 쿼리를 실행합니다.
- 추후에 공간 인덱스를 고려하였고, `ST_Within` 이라는 함수를 사용했습니다.
- h2 에서도 호환되기 위해 yml 파일 일부 수정했습니다.
> [UNI-64] 건물 노드 조회 API ([UNI-9] last PR)

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorResponse.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/CustomException.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/GlobalExceptionHandler.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/custom/SameStartAndEndPointException.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/custom/UnreachableDestinationException.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
예외를 추가하고자 할 시 다음과 같이 추가할 수 있습니다.
1. common/exception/custom 패키지 안에 예외 클래스 생성
2. common/exception/GlobalExceptionHandler.java에 ExceptionHandler 등록
3. 필요시 common/error/ErrorCode에 커스텀 에러코드 추가
4. 예외처리가 필요한 로직에서 사용
**example**
`throw new UnreachableDestinationException("Unable to find a valid route", ErrorCode.FASTEST_ROUTE_NOT_FOUND);`
RouteCalculationService에서 발생하는  예외처리를 추가하였습니다.
- 출발/도착지가 같은 경우 - SameStartAndEndPointException
- 경로를 찾을 수 없는경우 - UnreachableDestinationException 
CustomException 부모 클래스를 다른 exception이 상속받도록 수정하여 코드중복을 피하도록  하였습니다.
> [UNI-62] chore : custom exception handler 정의

- uniro_backend/build.gradle
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/CursorPage.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/QueryDSLConfig.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeApi.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/BuildingNode.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/GetBuildingResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/SearchBuildingResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/repository/BuildingCustomRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/repository/BuildingCustomRepositoryImpl.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/repository/BuildingRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/service/NodeService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/resolver/CautionListConverter.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/resolver/DangerListConverter.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/Route.java
1. 건물 노드를 검색하는 API 를 구현했습니다.
2. 만약 클라이언트의 요청값이 없을경우, where 조건에 제외하는 동적쿼리를 구현했습니다.
3. 페이지네이션 및 동적쿼리를 구현하기 위해 querydsl 를 사용했습니다.
1. offset를 활용한 페이지네이션이 아닌 cursor 기반으로 구현했습니다.
2. 이러한 방식이 성능적이나 기능적으로 더 좋다고 판단해서 그랬는데 다른 의견 있으시면 편하게 말씀주세요!
3. 커서 객체도 따로 정의했습니다!
4. cc. [커서 기반 페이지네이션 관련](https://velog.io/@znftm97/%EC%BB%A4%EC%84%9C-%EA%B8%B0%EB%B0%98-%ED%8E%98%EC%9D%B4%EC%A7%80%EB%84%A4%EC%9D%B4%EC%85%98Cursor-based-Pagination%EC%9D%B4%EB%9E%80-Querydsl%EB%A1%9C-%EA%B5%AC%ED%98%84%EA%B9%8C%EC%A7%80-so3v8mi2#span-stylecolor0b6e998-cursor%EB%A5%BC-custom%ED%95%B4%EC%84%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0span)
> [UNI-12] 건물 노드 검색 API

- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/controller/UnivAPI.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/controller/UnivController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/dto/SearchUnivResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/dto/UnivInfo.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/entity/Univ.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivCustomRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivCustomRepositoryImpl.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/service/UnivService.java
1. 대학교 이름을 기반으로 검색하는 API를 구현하였습니다.
2. 구현은 [UNI-12](https://github.com/softeer5th/Team2-Getit/pull/11)를 참고하여 기존 코드 스타일과 통일성을 유지하며 개발하였습니다.
[UNI-12]: https://uniro.atlassian.net/browse/UNI-12?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UNI-8] 전체 대학교 목록 조회(검색) API 구현

- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteApi.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/GetAllRoutesResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/CoreRoute.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/repository/CoreRouteRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
- 대학교 내 모든 루트와 노드를 조회하는 API를 개발하였습니다.
- 현재 리턴형식은 List형태로, 각각 coreRouteId, node1Id, node2Id, List<좌표> (길을 구성하는 각 노드의 좌표) 로 구성되어있습니다. 이는 추후 프론트엔드와의 의견조율로 변경될 수 있습니다.
- 현재 코어노드의 좌표를 따로 리턴하고있지 않습니다. 그 이유는 제공한 coreRoute의 양 끝이 코어노드이기 떄문에 데이터 중복을 피하기 위해서 입니다.
1. 현재 CoreRoute 테이블의 Path 컬럼 (LineString 타입)은 node1부터 시작하여 node2까지의 좌표입니다. 즉, 첫번째 좌표는 node1의 좌표이고 두번째 좌표는 node2의 좌표입니다.
- 만약 node1과 node2가 뒤바뀐 상태라면 로직상 문제가 발생합니다. 이를 검증하기 위한 로직이 **길 추가 API 개발** 에 필요합니다.
2. 과거엔 '코어노드 = 연결된 간선이 3개 이상인 갈림길' 로 정의되어있었습니다. 하지만 [코어노드 관련 논의 스레드](https://hmg5.slack.com/archives/C0874SWD998/p1738051305860579) 이후 '코어노드 = 연결된 간선이 3개 이상이거나 1개인 노드' 로 정의가 바뀌었습니다. 
[UNI-20]: https://uniro.atlassian.net/browse/UNI-20?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [UNI-11] feat : 대학교 내 모든 루트와 노드를 조회하는 API 개발

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/custom/DangerCautionConflictException.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/custom/RouteNotFoundException.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/utils/Utils.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteApi.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/GetRiskResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/PostRiskReqDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/Route.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/repository/RouteRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
특정 route의 주의/위험요소를 조회하는 API를 개발하였습니다.
input으로 route의 양끝 노드 좌표를 받아와 이를 통해 route를 조회한 뒤 응답하였습니다.
특정 route의 주의/위험요소를 업데이트하는 API를 개발하였습니다.
input으로 routeId와 리스트 형식의 주의,위험요소 factor를 받습니다.
만약 두 리스트가 모두 비어있다면 더이상 주의/위험요소가 없는 route로 간주하였습니다.
> [UNI-18] feat : route의 위험요소,주의요소 조회 및 업데이트(수정,삭제,생성) API 개발

- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/RouteDetailDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/RouteInfoDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
1. 차량 내비게이션 길찾기 형태에서 도보 길찾기 상세정보 형태로 응답을 변경하였습니다.
2. 길찾기 결과의 노드순서를 정렬하였습니다.
3. 길 상세정보 조회에서 갈림길에 해당하는 노드의 좌표를 추가하였습니다.
> [UNI-73] refactor : 길찾기 로직 응답형태 리팩토링

- uniro_backend/build.gradle
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/custom/ElevationApiException.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/client/MapClient.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/client/MapClientImpl.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/entity/Node.java
- uniro_backend/src/main/resources/application-local.yml
- uniro_backend/src/test/java/com/softeer5/uniro_backend/node/client/MapClientImplTest.java
- uniro_backend/src/test/resources/application-test.yml
- 외부 API를 호출해야하는 로직이므로 MapClient 인터페이스와 MapClientImpl 구현체로 구현하였습니다. 
- 길 추가 로직 1-3단계를 마친 배열에 대한 후처리 로직입니다. Service단에서 호출하여 사용하시면 될 것 같습니다.
플로우는 다음과 같습니다.
1. id가 null인 새로 추가된 Node 객체들을 필터링합니다. 이는 아직 데이터베이스에 저장되지 않은 새로운 POJO를 의미합니다.
2. Google Elevation API는 한 번에 최대 512개의 좌표만 처리할 수 있으므로, 필터링된 Node 객체들을 512개 단위로 파티셔닝합니다.
3. 파티셔닝된 각 배열을 WebClient를 이용해 비동기 병렬로 Google Elevation API에 요청을 보냅니다.
4. API 응답으로 받은 고도 데이터를 각 Node 객체의 z 값(height)에 매핑합니다.
5. 모든 비동기 API 요청이 완료될 때까지 Mono.when()으로 대기한 뒤, block()을 호출하여 동기적으로 결과를 반환합니다.
- 길 추가 로직에서 사용될 것으로 예상되어 Node 생성자의 Protected 접근자를 Public으로 변경하였습니다.
성공적으로 z좌표를 가져오는 시나리오와, 잘못된 API Key를 넘기는 등 예외가 발생하는 경우 정상적으로 ElevationApiException이 발생하는지 확인하는 테스트코드를 작성하였고, 정상 작동함을 확인하였습니다.
- yml에 ${google.api.key} 환경변수를 추가하였습니다. 저희 구글클라우드 계정에서 백엔드용 API Key를 넣어두셔야 정상적으로 작동할 …
> [UNI-86] feat : 길 추가 로직 - 4단계 (노드의 z좌표를 Google Map API를 호출하여 가져오기)

- uniro_frontend/src/App.tsx
- uniro_frontend/src/component/NavgationMap.tsx
- uniro_frontend/src/components/map/TopSheet.tsx
- uniro_frontend/src/components/map/mapMarkers.tsx
- uniro_frontend/src/components/report/formTitle.tsx
- uniro_frontend/src/components/report/primaryButton.tsx
- uniro_frontend/src/components/report/primaryForm.tsx
- uniro_frontend/src/components/report/reportDivider.tsx
- uniro_frontend/src/components/report/reportTitle.tsx
- uniro_frontend/src/components/report/secondaryButton.tsx
- uniro_frontend/src/components/report/secondaryForm.tsx
- uniro_frontend/src/constant/enum/markerEnum.ts
- uniro_frontend/src/constant/enum/reportEnum.ts
- uniro_frontend/src/constant/enum/routeEnum.ts
- uniro_frontend/src/constant/reportTheme.ts
- uniro_frontend/src/data/types/marker.d.ts
- uniro_frontend/src/data/types/report.d.ts
- uniro_frontend/src/data/types/report.ts
- uniro_frontend/src/data/types/route.d.ts
- uniro_frontend/src/hooks/useSearchBuilding.ts
- uniro_frontend/src/pages/map.tsx
- uniro_frontend/src/pages/reportForm.tsx
- uniro_frontend/src/utils/report/getThemeByPassableStatus.ts
- 제보 폼 페이지를 개발 완료했습니다.
```typescript
export interface ReportFormData {
passableStatus: PassableStatus;
dangerIssues: DangerIssueType[];
cautionIssues: CautionIssueType[];
}
```
Form Data는 백엔드와 사전에 이야기한 대로, 위험 / 주의 여부와, 위험 / 주의 배열들이 비어있으면 삭제로 판단하기로 했던 로직을 interface에 반영했습니다.
```typescript
export enum PassableStatus {
DANGER = "DANGER",
CAUTION = "CAUTION",
RESTORED = "RESTORED",
INITIAL = "INITIAL",
}
```
위 폼데이터에 들어있던 Type인 PassableStatus 타입은, 위험, 주의, 삭제, 초기로 나누었습니다.
가장 처음 로딩되었을 때, 혹은 버튼을 모두 해제하였을 때 초기로 설정하고, 나머지는 조건에 맞게 Status를 넘겨주었습니다.
대부분의 로직을, PassableStatus를 prop으로 넘겨주는 방식으로 처리하였습니다.
```typescript
import { PassableStatus } from "../../constant/enum/reportEnum";
export const getThemeByPassableStatus = (status: PassableStatus): string => {
const orangeTheme = "border-system-orange …
```
> [UNI-21] feat : 제보 폼 페이지 개발 (UNI-89, UNI-90)

- uniro_frontend/src/component/NavgationMap.tsx
- uniro_frontend/src/components/map/mapMarkers.tsx
- uniro_frontend/src/index.css
- 마커 등장 애니메이션을 구현했습니다.
```css
@keyframes markerAppear {
0% {
opacity: 0;
transform: scale(0);
}
100% {
opacity: 1;
transform: scale(1);
}
}
.marker-appear {
animation: markerAppear 0.3s ease-out forwards;
transform-origin: bottom center;
}
```
marker-appear class를 활용해 구현했습니다.
```typescript
function attachAnimation(container: HTMLElement, hasAnimation: boolean) {
if (hasAnimation) {
const outerContainer = document.createElement("div");
outerContainer.className = "marker-appear";
outerContainer.appendChild(container);
return outerContainer;
}
return container;
}
```
기존 마커 객체가 transform 속성을 이미 갖고 있어, 같은 level에 놓으면 둘 중에 하나만 동작합니다.
그래서 상위 div는 animation, 하위 div는 위치를 조정하도록 바꿨습니다.
```typescript
const container = createContainerElement(className);
export default function createMarkerElement({
if …
```
> [UNI-84] feat: 마커 등장 애니메이션 구현

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/custom/InvalidMapException.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteApi.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/CoreRouteDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/GetAllRoutesResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/NodeInfo.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/RouteCoordinatesInfo.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
코어 루트가 삭제되어 대학교의 모든 route를 조회하는 로직을 수정하였습니다.
- 코어노드 간에는 BFS로 이동하였으며, 코어노드와 코어노드 사이에 존재하는 서브노드들 (기존의 코어 루트)을 선형으로 탐색하여 List에 담아 처리하였습니다.
- 사이클, route 미존재, 코어노드가 없는 경우 등 예외처리를 진행하였습니다.
- 로직 특성상 코드가 길고 사용하는 변수가 많아서 읽기 어려울 것으로 예상됩니다. 최대한 주석을 달았지만, 이해되지 않는 부분 있으면 코멘트나 오프라인으로 질문해주시면 감사하겠습니다.
- BFS 로직 안에 존재하는 이중 while문을 분리하고 싶었으나 그렇게 될 경우 7,8개의 파라미터를 넘겨줘야 하는 상황입니다. 좋은 코드 수정 방향 있으면 조언 부탁드립니다.
- 현재 lat, lng가 반대로 출력되는것 같은데 같은 현상 겪고 계신지 확인 부탁드립니다.
<<테스트 결과>>
<<코어노드가 없는 (일자로 된 경우) 지도에서의 예외처리 테스트>>
> [UNI-100] refactor : 코어 루트 삭제에 따른 조회 로직 수정

- uniro_frontend/src/App.tsx
- uniro_frontend/src/hooks/useNetworkStatus.tsx
- uniro_frontend/src/hooks/useRedirectUndefined.tsx
- uniro_frontend/src/pages/buildingSearch.tsx
- uniro_frontend/src/pages/error.tsx
- uniro_frontend/src/pages/map.tsx
- uniro_frontend/src/pages/navigationResult.tsx
- uniro_frontend/src/pages/offline.tsx
- uniro_frontend/src/pages/reportForm.tsx
- uniro_frontend/src/pages/reportHazard.tsx
- uniro_frontend/src/pages/reportRoute.tsx
1. 네트워크 예외 (클라이언트 Offline, Online) 처리 로직 구현
2. 에러 페이지 (Offline, Error) 페이지 생성
3. 경로 예외 처리 (데이터 없이 URL로 접근하는 경우) 처리 로직 구현
```typescript
import { useEffect, useState } from "react";
import { useNavigate } from "react-router";
export default function useNetworkStatus() {
const [isOffline, setIsOffline] = useState<boolean>(false);
const navigate = useNavigate();
const handleOffline = () => {
setIsOffline(true);
navigate("/error/offline");
};
const handleOnline = () => {
setIsOffline(false);
navigate(-1);
};
useEffect(() => {
window.addEventListener("offline", handleOffline);
window.addEventListener("online", handleOnline);
return () => {
window.removeEventListener("offline", handleOffline);
window.removeEventListener("online", handleOnline);
};
});
}
```
- window에 offline, online 이벤트를 등록하여 …
> [UNI-105] feat : 예외 처리 로직 구현

- uniro_frontend/src/components/map/backButton.tsx
- uniro_frontend/src/components/map/reportButton.tsx
- uniro_frontend/src/components/map/reportModal.tsx
- uniro_frontend/src/pages/map.tsx
- uniro_frontend/src/pages/navigationResult.tsx
- uniro_frontend/src/pages/reportHazard.tsx
- uniro_frontend/src/pages/reportRoute.tsx
- uniro_frontend/src/pages/universitySearch.tsx
1. 페이지간 라우터 연결
2. 공통 뒤로가기 컴포넌트 생성
3. 지도 제보하기 모달 생성
```typescript
interface BackButtonProps {
className?: string;
onClick?: () => void
}
export default function BackButton({ className = "", onClick }: BackButtonProps) {
const navigate = useNavigate();
const handleBack = () => {
navigate(-1);
}
return (
<button className={`w-[52px] h-[52px] flex items-center justify-center border border-gray-400 rounded-full bg-gray-100 active:bg-gray-200 ${className}`} onClick={onClick ?? handleBack}>
<ChevronLeft width={35} height={35} />
</button>
)
}
```
- 기존 이미지로 버튼을 생성하던 컴포넌트를 다음과 같이 공통 컴포넌트로 뒤로가기 버튼을 생성하였습니다.
- className을 props로 받아서 직접적인 위치 조정을 수행합니다.
- onClick이 있는 경우에는 해당 로직을 수행하고 없다면 `navigate(-1)` 으로 뒤로가는 로직을 수행합니다.
```typescript
<BackButton onClick={hideDetailView} />
<BackButton …
```
> [UNI-108] feat : 페이지간 라우터 연결 및 뒤로가기 공통 컴포넌트 생성

- uniro_frontend/src/App.tsx
- uniro_frontend/src/container/dynamicSuspense.tsx
- uniro_frontend/src/hooks/useDynamicSuspense.tsx
- uniro_frontend/src/pages/navigationResult.tsx
전역 Suspense 페이지 전환 시 fallback 없이 freeze 되는 현상을 해결했습니다.
원인은 동료인 윤동현군의 예상대로 Router에서 Suspense를 제대로 처리하지 못하는 문제였습니다.
react-router 6.12 버전부터 생겼던 버그로, 오래전부터 많은 사람들이 겪어왔던 것 같습니다
[Issue 링크](https://github.com/remix-run/react-router/issues/10568)
Suspense의 key를 location의 key를 넣어주어, Suspense를 trigger 해주는 것 같은 원리인 것 같습니다.
하루종일 Suspense에 대해서 공부했는데 이런 해결책이라 좀 허무하지만, 그래도 머릿속에 어떤 원리로 동작하는지 공부하게 되었던 것 같습니다.
기존 문제
https://github.com/user-attachments/assets/1aae683d-183d-445a-9fd5-449deb41e0d1
해결된 동작
https://github.com/user-attachments/assets/42d0b159-6ac0-4903-b1ac-bf7daab3a47d
> [UNI-116] fix : 전역 Suspense 페이지 전환 시 fallback 없이 freeze 되는 현상 해결

- uniro_frontend/src/assets/markers/university.svg
- uniro_frontend/src/components/map/reportModal.tsx
- uniro_frontend/src/data/types/node.d.ts
- uniro_frontend/src/pages/map.tsx
- uniro_frontend/src/utils/markers/createAdvanedMarker.ts
1. 지도 페이지 뷰포트 조정
2. 마커 동적 스타일 변경 로직 오류 해결
3. 한 건물을 출발, 도착 동시 지정 불가 적용
4. 제보하기 모달 PC환경 스타일 조정
5. 줌 레벨 변화에 따른 마커 노출 로직 신규 적용
| before  | After |
| ------------- | ------------- |
| <video src="https://github.com/user-attachments/assets/f92d9dd5-6c86-4af9-90c8-579207a2afeb">  | <video src="https://github.com/user-attachments/assets/10a30099-0b02-4f33-836b-de59fb75a71a">|
- 기존에는 위험 주의 요소 마커의 콘텐츠를 변경하는 로직이 addListener로 여러 곳에 분산이 되어 있는 로직을 건물 마커 컨텐츠를 수정하는 useEffect의 로직으로 통일하였습니다.
- before
```typescript
const initMap = () => {
if (map === null) return;
map.addListener("click", (e: unknown) => {
setSheetOpen(false);
setSelectedMarker((marker) => {
if (marker) {
const { type, element } = marker;
if (type === Markers.BUILDING) return undefined;
element.content = createMarkerElement({ type });
} …
```
> [UNI-111] fix, feat, refactor : QA 문제 해결 (지도 페이지 뷰포트, 마커  동적 스타일 변경, 지도 줌 레벨 감지, 제보하기 모달 PC 환경 스타일)

- .github/workflows/be-cd.yml
- .github/workflows/be-ci.yml
- uniro_backend/Dockerfile
- uniro_backend/build.gradle
- uniro_backend/docker-compose.yml
- uniro_backend/src/main/resources/application-dev.yml
- uniro_backend/src/main/resources/application-test.yml
- uniro_backend/src/test/java/com/softeer5/uniro_backend/node/client/MapClientImplTest.java
- ci/cd 구축했습니다.
- 깃헙 액션 -> docker hub -> ec2 -> 배포 스크립트 실행 구조입니다.
- 유지보수성을 고려하여 모든 환경을 `Dockerizing` 하여 구축했습니다.
- feat/
> [UNI-65] feat: ci-cd 구축

- uniro_frontend/package-lock.json
- uniro_frontend/package.json
- uniro_frontend/src/App.tsx
1. Tanstack Query DevTools 라이브러리 설치
- API 연결을 앞두고 클라이언트에서 데이터 캐싱을 실제로 확인 및 refetch 등 다양한 유틸을 사용하기 위해 라이브러리를 설치하였습니다.
> [UNI-120] feat : Tanstack-Query  DevTools 라이브러리 설치 및 적용

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/SwaggerConfig.java
- uniro_backend/src/main/resources/application-local.yml
- 스웨거 관련 cors 오류를 해결했습니다.
- feat/
> [UNI-126] chore: 스웨거 cors 오류 해결

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/constant/UniroConst.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/utils/GeoUtils.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/external/MapClient.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/external/MapClientImpl.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/node/entity/Node.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteApi.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/CreateRouteCoordinates.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/CreateRouteReqDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/Route.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
- uniro_backend/src/test/java/com/softeer5/uniro_backend/node/client/MapClientImplTest.java
- uniro_backend/src/test/java/com/softeer5/uniro_backend/route/RouteCalculationServiceTest.java
- 5단계 노드를 저장하고, route를 생성합니다.
- 중복된 node가 저장되지 않도록 Set을 통해 필터링 하였습니다.
- SRID 4326으로 데이터베이스에 저장하기 위해 다음과 같은 코드를 추가하였습니다.
`new GeometryFactory(new PrecisionModel(), 4326)`
- 현재 프론트엔드와 협업을 통해 테스트를 진행해야하는 상황입니다.
- 코드 구조와 로직이 미완성인 상태입니다. 추후 테스트를 통해 리팩토링할 예정입니다.
> [UNI-87] 길추가 로직 4,5단계 구현 (리팩토링 예정)

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/logging/ExecutionLoggingAop.java
- 로깅 aop를 구현했습니다.
- 로깅 내용은 아래와 같습니다.
- userId (스레드 로컬마다 고유하게 있는 id)
- 요청 클래스, 요청 메서드
- 요청 파라미터
- 실행시간
- 시작점, 종료점 표시
- 최초 요청에는 다른 요청과 구분하기 위해 ✅ 표시를 해뒀습니다.
- 추가로 controller 단에서는 HTTP request 메세지 원문 그대로를 로깅합니다. 저희 웹서버 구현하면서 rfc 문서와도 많이 친해졌으니 해당 값을 로깅하면 많은 도움이 될 것 같았습니다! 그래서 해당 메세지를 로깅했습니다.
- 스레드는 재사용되기 때문에 controller 단에서 userId를 할당 및 해제 해줬습니다.
- feat/
> [UNI-66] feat: 로깅 aop 구현

- uniro_backend/src/main/java/com/softeer5/uniro_backend/resolver/CautionListConverter.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/resolver/DangerListConverter.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/GetCautionResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/GetDangerResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/Route.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/repository/RouteRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
- dangerFactors가 비어있는 경우에도 위험 요소로 잘못 판단되어 응답되는 문제를 해결하였습니다.
- dangerFactors만 존재하는 경우를 올바르게 처리하도록 예외 처리를 추가하였습니다.
- dangerFactors, cautionFactors 필드는 DB에서 JSON 형식의 VARCHAR로 저장되며, converter를 통해 애플리케이션 레벨에서는 Set<T>로 사용되고 있었습니다.
- 해당 필드가 nullable한 상태여서 매번 null 체크가 필요했으며, 이는 불필요한 런타임 오류 발생 가능성 증가 및 협업 효율 저하로 이어졌습니다.
- 또한, 데이터 조회 시 빈 배열([])과 null을 구분하기 어려운 문제가 있었습니다.
- dangerFactors, cautionFactors를 NOT NULL로 변경하고 기본값을 []로 설정하는 컨벤션을 도입
- Converter를 활용하여 기본값을 항상 []로 유지하도록 변경
- 데이터 조회 시 startWith("[\") 조건을 사용할 수 있어 인덱스를 효과적으로 활용 가능
- null과 []를 구분해야 하는 문제를 해결하여 런타임 오류 방지 및 코드 가독성 향상
결과적으로, 위험 요소가 있는 route 조회 로직이 더욱 직관적이고 안정적으로 동작할 수 있도록 개선되었습니다.
> [UNI-134] fix : 분기문 오류로 인한 잘못된 응답 수정

- uniro_frontend/src/api/route.ts
- uniro_frontend/src/api/transformer/route.ts
- uniro_frontend/src/api/type/request/route.d.ts
- uniro_frontend/src/api/type/response/route.d.ts
- uniro_frontend/src/components/report/secondaryButton.tsx
- uniro_frontend/src/components/report/secondaryForm.tsx
- uniro_frontend/src/constant/enum/reportEnum.ts
- uniro_frontend/src/data/types/enum.d.ts
- uniro_frontend/src/data/types/report.d.ts
- uniro_frontend/src/data/types/route.d.ts
- uniro_frontend/src/data/types/university.d.ts
- uniro_frontend/src/hooks/useDynamicSuspense.tsx
- uniro_frontend/src/hooks/useModal.tsx
- uniro_frontend/src/hooks/useUniversityInfo.tsx
- uniro_frontend/src/pages/reportForm.tsx
- uniro_frontend/src/utils/fetch/fetch.ts
1. 제보 Form API를 연결했습니다
2. fallback의 console.log을 삭제했습니다.
백엔드 요청이 전부 Key값으로 요청이 전달되어, Key값으로 State가 저장되도록 변경했습니다. 
```typescript
export const SecondaryFormButton = ({
onClick,
formPassableStatus,
isSelected,
contentKey,
}: {
onClick: (answer: IssueTypeKey) => void;
formPassableStatus: PassableStatus;
isSelected: boolean;
contentKey: IssueTypeKey;
}) => {
return (
<button
onClick={() => onClick(contentKey)}
className={`mb-3 mr-3 py-[18px] px-[22px] border-[1px] rounded-[20px] w-fit text-kor-body2 border-gray-400 ${isSelected && getThemeByPassableStatus(formPassableStatus)}`}
>
{formPassableStatus === PassableStatus.CAUTION
? CautionIssue[contentKey as CautionIssueType]
: DangerIssue[contentKey as DangerIssueType]}
</button>
);
};
```
- 수정 상태에서 danger, caution state들이 서로 왔다갔다 할 때, 값이 보존되는 …
> [UNI-140] feat : 제보 Form API 연결

- uniro_frontend/src/data/types/route.d.ts
- uniro_frontend/src/pages/reportHazard.tsx
- uniro_frontend/src/pages/reportRoute.tsx
1. 길 조회 API를 연결했습니다.
제가 길을 백엔드에 잘못 줘서.. 아마 꺾이는 길에서 계속 5번 라우트가 뜰 예정입니다. 정상이니까 당황하지 마시고, 오히려 제보 테스트에 사용하면 좋을 거 같습니다~!
https://github.com/softeer5th/Team2-Getit/pull/65 이 PR에서 길 조회 API를 만들어 놓았었는데, transformer까지 적용시켜 잘 만들어놓았습니다. 좀 불편한 부분은 nodeId를 다이렉트로 map 형태로 가져올 수 있는 데이터가 없는데 처음 시작과 끝에서 그릴 때 처음 index와 마지막 index를 활용해야 한다는 점이 cost입니다.
연결한 페이지는
1. 제보 페이지
2. 길 추가 페이지
두가지 페이지에 모두 다 연결했습니다.
기존 로직은 하나의 Path에 대해서 그리는 방식이었는데, 조금 응용해서 2중 for문을 사용했습니다.
데이터 불러오는 속도 자체는 매우 빨라서, 사용자 입장에서 Overhead가 적은 것 같습니다. 나중에 개발자 창으로 Data가 얼마나 오는지 같이 확인해보면 좋을 것 같습니다.
```typescript
const drawRoute = (coreRouteList: CoreRoutesList) => {
if (!Polyline || !AdvancedMarker || !map) return;
for (const coreRoutes of coreRouteList) {
// 가장 끝쪽 Core Node 그리기
const endNode = coreRoutes.routes[coreRoutes.routes.length - 1].node2; …
```
> [UNI-141] feat : 길 조회 API 연결

- uniro_frontend/src/pages/buildingSearch.tsx
- uniro_frontend/src/pages/error.tsx
- uniro_frontend/src/pages/landing.tsx
- uniro_frontend/src/pages/navigationResult.tsx
- uniro_frontend/src/pages/offline.tsx
- uniro_frontend/src/pages/reportForm.tsx
- uniro_frontend/src/pages/universitySearch.tsx
1. 현재 있는 화면들 중 h-screen 부분을 h-dvh로 변경했습니다.
일반적인 브라우저 화면에서 사용자에게 보여지는 화면 범위를 viewport라고 정의합니다. 이 viewport는 PC에서는 신경 쓸 일이 없지만, mobile의 경우 화면들의 구성요소들의 밀도가 높고, 화면이 작으면서 브라우저가 보여지는 영역까지 달라져 viewport가 자체 OS나 브라우저에 의해 가려지는 부분이 있습니다.
스마트폰이 보급되고, 많은 사람들이 스마트 기기를 활용해 인터넷을 접속하게 되면서, 매번 기기 정보를 받아와 어떤 화면 범위를 보여주라고 정의를 할 수 없게 되었습니다 그래서 이를 자동으로 전환해주는 CSS 속성이 2019년에 출시되었고, dynamic하게 viewport를 설정할 수 있게 되었습니다.
저희 웹은 지도를 사용하기 때문에 스크롤 경험이 사용성에 중요한 영향을 미치는데, 이를 고려해 더욱 좋은 사용성과 UI를 위해 전환했습니다.
h-screen으로 동작하는 화면은 모두 h-dvh로 전환했습니다.
> [UNI-143] fix : 스크린 사이즈 dvh로 통일하기

- uniro_frontend/src/pages/reportRoute.tsx
1. 지도 페이지 모달을 통한 제보 페이지 이동 라우터 수정
- 2개의 꺾인 길 생성 시, (1, 2, 3, 4, 5) , (5, 6, 7, 8)을 그대로 삽입하여 [1, 2, 3, 4, 5, 5, 6, 7, 8] 이 되어 API오류가 발생하는 문제 해결
```typescript
const reportNewRoute = () => {
if (!newPolyLine.current || !Polyline) return;
const subNodes = [];
const edges = newPoints.coords.map((node, idx) => [node, newPoints.coords[idx + 1]]).slice(0, -1);
for (const edge of edges) {
const subNode = createSubNodes(new Polyline({ path: edge }));
subNodes.push(...subNode);
}
if (!originPoint.current) return;
const lastPoint = newPoints.coords[newPoints.coords.length - 1] as Node | Coord;
}
```
- subNode를 그대로 복사하여 삽입하는 것이 아닌
```typescript
const reportNewRoute = () => {
if (!newPolyLine.current || !Polyline) return;
const subNodes = [];
const edges = newPoints.coords.map((node, idx) => [node, …
```
> [UNI-149] fix : 중복 포인트 삽입 문제 해결 (1, 2, 3, 4, 5, 5, 6, 7, 8) 문제

- uniro_frontend/src/component/NavgationMap.tsx
- uniro_frontend/src/components/map/mapMarkers.tsx
- uniro_frontend/src/components/navigation/navigationDescription.tsx
- uniro_frontend/src/components/navigation/route/routeCard.tsx
- uniro_frontend/src/components/navigation/route/routeList.tsx
- uniro_frontend/src/hooks/useRoutePoint.ts
- uniro_frontend/src/index.css
- uniro_frontend/src/pages/buildingSearch.tsx
- uniro_frontend/src/pages/error.tsx
- uniro_frontend/src/pages/landing.tsx
- uniro_frontend/src/pages/navigationResult.tsx
- uniro_frontend/src/pages/offline.tsx
- uniro_frontend/src/pages/reportForm.tsx
- uniro_frontend/src/pages/universitySearch.tsx
- uniro_frontend/src/utils/navigation/formatDistance.ts
1. 길찾기 페이지 API를 연결했습니다.
```typescript
const result = useSuspenseQueries({
queries: [
{
queryKey: ["fastRoute", university?.id, origin?.nodeId, destination?.nodeId],
queryFn: async () => {
try {
const response = await getNavigationResult(
university?.id ?? 1001,
originId ? Number(originId) : origin?.nodeId,
destinationId ? Number(destinationId) : destination?.nodeId,
);
setOriginCoord(response.routes[0].node1.lng, response.routes[0].node1.lat);
setDestinationCoord(
response.routes[response.routes.length - 1].node1.lng,
response.routes[response.routes.length - 1].node1.lat,
);
return response;
} catch (e) {
return null;
}
},
retry: 1,
},
{ queryKey: [university?.id, "risks"], queryFn: () => getAllRisks(university?.id ?? 1001), retry: 1 },
],
});
```
retry는 우선 한번으로 통제했고, key로 cache가 가능하도록 …
> [UNI-127] feat : 길찾기 페이지 API 연결

- uniro_frontend/src/api/transformer/route.ts
- uniro_frontend/src/component/NavgationMap.tsx
- uniro_frontend/src/components/navigation/route/routeCard.tsx
- uniro_frontend/src/components/navigation/route/routeList.tsx
- uniro_frontend/src/data/types/route.d.ts
- uniro_frontend/src/hooks/useNavigationBottomSheet.tsx
- uniro_frontend/src/pages/navigationResult.tsx
- uniro_frontend/src/utils/navigation/formatDistance.ts
1. 금요일에 백엔드에 요청드린 API 변경사항에 맞춰, 프런트의 코드를 변경했습니다.
2. 백엔드가 예외나 에러를 리턴할 때, 내용을 볼 수 있도록 alert를 임시로 추가했습니다.
3. m단위일때의 포맷 변환 처리를 해놓지 않아, 그 부분을 처리했습니다.
4. 길 찾기의 바텀시트 디자인 요구사항에 맞게 하단으로 드래그 했을 때 스크롤이 불가능하도록 했습니다.
5. 바텀 시트 관련 기능들이 너무 많아, 따로 hook으로 분리했습니다.
6. cautionFactors로 내비게이션 관련 type을 변경했습니다.
7. 우회전, 좌회전 텍스트에서 급격한 우회전, 급격한 좌회전 텍스트를 추가했습니다.
```typescript
export const formatDistance = (distance: number) => {
if (distance < 1) {
return `${Math.ceil(distance * 1000) / 1000}m`;
}
if (distance < 1000) {
return `${Math.ceil(distance)}m`;
}
return distance >= 1000
? `${(distance / 1000).toFixed(1)} km` // 1000m 이상이면 km 단위로 변환
: `${distance} m`; // 1000m 미만이면 m 단위 유지
};
```
```typescript
const preventScroll = useCallback(
(event: React.UIEvent<HTMLDivElement>) => {
if (sheetHeight < MAX_SHEET_HEIGHT * …
```
> [UNI-168] feat : 백엔드 API 변경사항 적용 및 코드 리팩토링

- uniro_admin_frontend/src/App.tsx
- uniro_admin_frontend/src/AppRouter.tsx
- uniro_admin_frontend/src/components/navBar.tsx
- uniro_admin_frontend/src/components/subNavBar.tsx
- uniro_admin_frontend/src/main.tsx
- uniro_admin_frontend/src/page/buildingPage.tsx
- uniro_admin_frontend/src/page/logPage.tsx
- uniro_admin_frontend/src/page/simulationPage.tsx
1. Router로 페이지별 작업 환경을 설정했습니다.
```typescript
function App() {
return (
<div className="w-full h-screen flex flex-col items-center justify-center space-y-1">
<NavBar />
<SubNavBar />
<Outlet />
</div>
);
}
```
Outlet을 활용해 NavBar, SubNavBar을 공통으로 사용할 수 있도록 했습니다.
https://github.com/user-attachments/assets/6ffa1999-3022-41b1-8d4b-e726e91465c9
> [UNI-175] feat : Router로 페이지별 작업 환경 설정하기

- uniro_frontend/src/App.tsx
- uniro_frontend/src/components/error/ErrorBoundary.tsx
- uniro_frontend/src/constant/error.ts
- uniro_frontend/src/hooks/useMutationError.tsx
- uniro_frontend/src/pages/errorTest.tsx
- uniro_frontend/src/utils/fetch/fetch.ts
1. 에러 바운더리 생성
2. POST 요청 시, 에러 핸들링 로직
- Error 발생 시, 보여줘야 할 fallback을 생성하기 위한 Global ErrorBoundary를 구현해야 했습니다.
- 기존 react에서도 [권장](https://react.dev/reference/react/useTransition#displaying-an-error-to-users-with-error-boundary)하는 [react-error-boundary](https://www.npmjs.com/package/react-error-boundary) 라이브러리가 존재하나 조금 더 자유로운 커스텀을 위해 직접 구현하였습니다.
- [getDerivedStateFromError](https://react.dev/reference/react/Component#static-getderivedstatefromerror)를 사용하였습니다.
```typescript
import React, { Component, ReactNode } from 'react';
interface ErrorBoundaryProps {
fallback: ReactNode;
}
interface ErrorBoundaryState {
hasError: boolean;
}
export default class ErrorBoundary extends Component<
React.PropsWithChildren<ErrorBoundaryProps>,
ErrorBoundaryState
> {
constructor(props: …
```
> [UNI-145] feat : 에러 바운더리 생성 및 POST 에러 핸들링 로직

- uniro_frontend/src/pages/errorTest.tsx
> [UNI-145] fix : 에러 테스트 페이지 백엔드 API 요청, 필드명 변경

- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/CoreRouteResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
- 길찾기 로직에서 좌/우회전이 반대로 적용되던 오류 수정
- cord2Node -> core2Node로 오타수정
> [UIN-184] 길찾기 로직에서 좌/우회전이 반대로 적용되던 오류 수정

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/GlobalExceptionHandler.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/request/CreateRoutesReqDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/request/PostRiskReqDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
- 클라이언트로부터 잘못된 값을 입력 받았을 때 검증하는 로직을 작성했습니다.
- feat/
> [UNI-178], [UNI-179] fix : 클라이언트 요청값 검증 로직 구현

- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
- uniro_backend/src/test/java/com/softeer5/uniro_backend/route/RouteCalculationServiceTest.java
- 기존 선과 동일한 경우 예외 발생하는 부분에서 버그가 있었습니다.
- 기본 크로스 체크와 self 크로스 체크를 구분하기 위해 플래그성 파라미터를 추가했습니다.
- 테스트 코드 참고.
- feat/
> [UNI-185] fix: 기존 선과 동일하거나 겹치는 경우 예외 발생 (일반 크로스 체크와 self 크로스에 따라 분기처리)

- uniro_frontend/src/assets/undo.svg
- uniro_frontend/src/components/map/floatingButtons.tsx
- uniro_frontend/src/hooks/useMap.tsx
- uniro_frontend/src/map/initializer/googleMapInitializer.ts
- uniro_frontend/src/map/loader/googleMapLoader.ts
- uniro_frontend/src/pages/reportRisk.tsx
- uniro_frontend/src/pages/reportRoute.tsx
- uniro_frontend/src/utils/coordinates/centerCoordinate.ts
- uniro_frontend/src/utils/coordinates/distance.ts
- uniro_frontend/src/utils/markers/removeMarkers.ts
- uniro_frontend/src/utils/markers/toggleMarkers.ts
- uniro_frontend/src/utils/polylines/createSubnodes.ts
- uniro_frontend/src/utils/polylines/findNearestEdge.ts
1. 구글 구면좌표계 도입
2. (QA 수정 사항) 새로운 길 제보 성공/실패 시 임시 생성 waypoint 마커 제거
3. 새로운 길 제보 시, 되돌리기 기능 구현
- #32 에서 언급된, 직선 계산으로 인한 길이 비직선형인 문제를 해결하기 위해서 구글 구면 좌표계를 도입하였습니다.
-[구글맵 SDK](https://developers.google.com/maps/documentation/javascript/geometry?hl=ko) 에서 사용할 함수는 interpolate와 computeLength 입니다.
- interpolate 메소드로 createSubNode, distance 및 centerCoordinate 함수를 대체할 수 있습니다.
```typescript
/** 구면 보간 없이 계산한 결과 */
export default function createSubNodes(
spherical: typeof google.maps.geometry.spherical | null,
polyLine: google.maps.Polyline,
): Coord[] {
const paths = polyLine.getPath();
const [startNode, endNode] = paths.getArray().map((el) => LatLngToLiteral(el));
const length = distance(spherical, startNode, endNode);
console.log("구면 보간", length);
const subEdgesCount = Math.ceil(length / …
```
> [UNI-167] feat, fix, refactor : 구글 구면좌표계 도입, QA waypoint 마커 제거, 새로운 길 제보시 되돌리기 기능 구현

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/utils/RouteUtils.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
- 모든 노드와 간선을 조회하는 로직에서 빌딩노드와 연결된 간선은 조회되지 않도록 로직을 수정하였습니다.
- 추가로 사이클이 돌며, 코어노드가 없는 경우 예외처리 하였는데, 처리 가능하도록 로직을 수정하였습니다.
- feat/UNI-156 에서 판 브렌치입니다.
> [UNI-158] fix : 빌딩노드와 연결된 간선은 조회되지 않도록 로직 수정

- uniro_frontend/src/pages/navigationResult.tsx
1. Param으로 받는 기능을 유지할 필요성을 느껴, 우선 유지하고 길찾기 결과에서 건물을 선택했을 경우 건물로 출발과 도착지 마커가 이동하도록 변경했습니다.
> [UNI-187] fix : Param으로 받지 않고, Building으로 검색했을 때 위치가 변동되지 않는 문제 해결

- uniro_frontend/src/hooks/useMutationError.tsx
- uniro_frontend/src/pages/errorTest.tsx
- uniro_frontend/src/pages/navigationResult.tsx
- uniro_frontend/src/pages/reportForm.tsx
- uniro_frontend/src/pages/reportRoute.tsx
1. useMutationError 리팩토링
2. useMutation -> useMutationError 적용
- #88 에서 생성한 useMutationError를 리팩토링 하였습니다.
```typescript
type Fallback = {
[K in Exclude<ERROR_STATUS, ERROR_STATUS.INTERNAL_ERROR>]: {
mainTitle: string;
subTitle: string[];
};
};
type HandleError = {
fallback: Fallback;
onClose?: () => void;
}
type UseMutationErrorReturn<TData, TError, TVariables, TContext> = [
React.FC,
UseMutationResult<TData, TError, TVariables, TContext>
];
export default function useMutationError<TData, TError, TVariables, TContext>(
options: UseMutationOptions<TData, TError, TVariables, TContext>,
queryClient?: QueryClient,
handleError?: HandleError,
): UseMutationErrorReturn<TData, TError, TVariables, TContext> {
const [isOpen, setOpen] = useState<boolean>(false);
const result = useMutation<TData, …
```
> [UNI-188] refactor : 불편한 길 제보 페이지 & 새로운 길 제보 페이지 useMutation -> useMutationError 변경

- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
- 길 찾기 로직에서 출발점or도착점이 건물노드이지만, 연결된 간선이 없는 경우 Node Not Found -> Fastest Route Not Found로 변경하였습니다.
- 빌딩과 연결된 루트의 양 끝 노드가 각각 출발점과 도착점인 경우 발생하던 오류를 수정하였습니다.
…-> Fastest Route Not Found로 변경
- 2번과 36번 노드는 직접 연결되어있으며, 36번노드는 빌딩노드이다.
- 33번 노드 : 아무 노드와도 연결되어있지 않은 빌딩노드
> [UNI-192] QA : 길찾기 로직 예외처리 수정

- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/BuildingRouteResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/GetAllRoutesResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
- 특정 대학의 모든 길 조회 로직에서 building과 연결된 루트도 조회되도록 수정하였습니다. (일반 route들과는 다른 배열에 담아서 제공합니다.)
> [UNI-193] 모든 길 조회 로직에서 building route를 따로 제공하는 로직 추가

- uniro_frontend/src/components/navigation/navigationDescription.tsx
- uniro_frontend/src/constant/error.ts
- uniro_frontend/src/hooks/useQueryError.tsx
- uniro_frontend/src/pages/map.tsx
- uniro_frontend/src/utils/fetch/fetch.ts
1. useQueryError 도입 (GET 요청 시, ErrorHandle)
2. 422 에러 추가
- 빠른 길 찾기 기능에서 건물과 건물 사이의 경로를 탐색할 수 없는 경우 422 에러가 return 되어 추가하였습니다.
- 빠른 길 찾기 422에러가 발생한 경우, 사용자에게 경로를 찾을 수없다는 모달을 제공하기 위해 useQueryError를 도입하였습니다.
- #88 에서 생성한 useMutationError와 동일한 형태로 구현하였습니다.
```typescript
import { QueryClient, useQuery, UseQueryOptions, UseQueryResult } from "@tanstack/react-query";
import { NotFoundError, BadRequestError, ERROR_STATUS, UnProcessableError } from "../constant/error";
import { useEffect, useState } from "react";
type Fallback = {
[K in Exclude<ERROR_STATUS, ERROR_STATUS.INTERNAL_ERROR>]?: {
mainTitle: string;
subTitle: string[];
};
};
type HandleError = {
fallback: Fallback;
onClose?: () => void;
}
type UseQueryErrorReturn<TData, TError> = [
React.FC,
UseQueryResult<TData, TError>
];
export …
```
> [UNI-196] feat : 길찾기 결과 경로 없음 에러(422) 화면 및 커스텀 훅 추가

- uniro_frontend/src/pages/reportForm.tsx
1.  일부 모바일 브라우저에서 form이 x축으로 스크롤이 가능한 문제를 해결했습니다.(overflow-x-hidden 추가)
https://github.com/user-attachments/assets/29b96b86-f4df-4dd7-85ea-215a4a672c98
https://github.com/user-attachments/assets/07e84b2d-dc5f-45de-84e0-ae44ab007946
> [UNI-207] fix : 일부 모바일 브라우저에서 form이 x축으로 스크롤이 가능한 문제

- uniro_frontend/src/hooks/useDebounceMutation.tsx
- uniro_frontend/src/hooks/useMutationError.tsx
- uniro_frontend/src/pages/reportForm.tsx
- uniro_frontend/src/pages/reportRoute.tsx
1. Post 요청에 대해 debounce를 적용했습니다.
2. debounce를 custom hook으로 변경해, 동현님이 제작한 useMutationError hook에 병합했습니다.
제작한 debounce를 검증하기 위해 mock과 console을 활용해 테스트하다가, 길 생성 API의 실제 테스트를 하기 위해서 실제 API로 따닥 테스트를 했습니다.
그 결과, 백엔드의 길 조회 API에 장애를 일으켜 잠깐 백엔드 개발 서버의 응답이 느려지는 결과가 있었습니다. 알고보니, debounce를 테스트하고 있었던 개발 환경이 아니라, debounce가 배포되지 않은 배포 사이트에서 테스트하고 있었습니다.
따닥 테스트로 추가된 똑같은 두가지 길을 제거하고, 서버를 재배포해 해결되었습니다.
멘토님과 팀원들과 이야기하며, 현업에서는 절대 이런 식으로 테스트 안된다는 것을 깨달았고, 다음에는 꼭 백엔드와 협의하고, 안전한 상황에서 테스트를 할 수 있도록 하려고 합니다.
또한, 테스트 코드도 이런 부분들은 꼭 작성해야 한다는 것을 깨달았고, 개발환경에서 테스트를 하고 있는지도 꼭 확인해보겠습니다.
백엔드가 QA에서 말씀해주시기도 해서 도입한 이유도 있지만, 저는 이전 프로젝트에서 같은 요청을 빠른 따닥(?)으로 중복 요청해 게시물이 여러개가 올라가는 경험을 했었습니다. 그럴 때마다 해결할 때 라이브러리를 사용하거나,loading(pending) 상태일 때 버튼을 비활성화하는 방법을 사용했습니다.
하지만 state를 변경하면서 loading이나 pending 상태로 전환되는 그 찰나에 작동하는 따딱이 있었고, 그런 …
> [UNI-195] Post 요청에 대한 debounce 적용

- uniro_frontend/src/hooks/useMutationError.tsx
- uniro_frontend/src/map/initializer/googleMapInitializer.ts
- uniro_frontend/src/pages/map.tsx
- uniro_frontend/src/pages/reportForm.tsx
- uniro_frontend/src/utils/fetch/fetch.ts
1. 지도 메인페이지 줌 아웃시 위험 주의 비활성화 로직 제거
2. 불편한 길 반영 시, 잔여 캐시로 인한 제보 확인 불가 해결
3. 지도 제스쳐 핸들링 방식 변경
```typescript
useEffect(() => {
if (!map) return;
const _buildingMarkers = buildingMarkers.map((buildingMarker) => buildingMarker.element);
if (prevZoom.current >= 17 && zoom <= 16) {
if (isCautionAcitve) {
toggleMarkers(
false,
cautionMarkers.map((marker) => marker.element),
map,
);
}
if (isDangerAcitve) {
toggleMarkers(
false,
dangerMarkers.map((marker) => marker.element),
map,
);
}
toggleMarkers(true, universityMarker ? [universityMarker] : [], map);
toggleMarkers(false, _buildingMarkers, map);
} else if (prevZoom.current <= 16 && zoom >= 17) {
if (isCautionAcitve) {
toggleMarkers(
true,
cautionMarkers.map((marker) => marker.element),
map,
);
}
if (isDangerAcitve) {
toggleMarkers(
true, …
```
> [UNI-201] fix : (QA 수정 사항) 지도 메인페이지 줌 아웃시 위험 주의 비활성화 로직 제거 / 불편한 길 반영 시, 캐시 초기화 적용 / 지도 제스쳐 핸들링 방식 변경

- uniro_frontend/src/hooks/useMap.tsx
- uniro_frontend/src/map/initializer/googleMapInitializer.ts
- uniro_frontend/src/map/loader/googleMapLoader.ts
- uniro_frontend/src/pages/reportRisk.tsx
- uniro_frontend/src/pages/reportRoute.tsx
- uniro_frontend/src/utils/coordinates/centerCoordinate.ts
- uniro_frontend/src/utils/coordinates/distance.ts
- uniro_frontend/src/utils/interpolate.ts
- uniro_frontend/src/utils/polylines/createSubnodes.ts
- uniro_frontend/src/utils/polylines/findNearestEdge.ts
1. interpolate 함수 구현
2. distance 함수 로직 변경
3. 구글 구면 좌표계 제거
- 백엔드로부터 새로운 길 제보시 중복 포인트 삽입이 발생한다는 것을 인지하여 문제를 해결하였습니다.
- 2~3m의 작은 길을 생성하여 샘플링 시, 중복포인트가 발생한다는 것을 확인하여 원인을 분석한 결과, #98 에서 도입한 구글 geometry 라이브러리에서 interpolate 시 발생하는 문제였습니다.
- @jpark0506 준혁님께서 비슷한 사례 [Google Issue Tracker](https://issuetracker.google.com/issues/260343763?pli=1) [StackOverflow](https://stackoverflow.com/questions/7636546/google-maps-v3-geometry-library-interpolate-does-not-return-expected-lat-lng)를 찾아주신 덕분에 짧은 거리에 대해 interpolate 시킬 경우, Google SDK에서 계산하는 로직으로는 좌표가 소수점 5번째 이하부터는 동작하지 않는 것을 확인하여 쉽게 해결할 수 있었습니다.
```javascript
Zt.interpolate = function(a, b, c) {
a = _.Se(a);
b = _.Se(b);
var d = _.Pe(a)
, e = _.Qe(a)
, f = _.Pe(b)
, g = _.Qe(b)
, h = Math.cos(d)
, k = Math.cos(f);
b = Zt.Js(a, b);
var l = Math.sin(b); …
```
> [UNI-215] fix : 구글 구면좌표계 제거 및 interpolate 함수 및 distance 함수 구현

- uniro_frontend/package-lock.json
- uniro_frontend/package.json
- uniro_frontend/src/components/map/TopSheet.tsx
- uniro_frontend/src/components/map/mapBottomSheet.tsx
- uniro_frontend/src/pages/map.tsx
1. react-spring-bottom-sheet 라이브러리 제거
2. 라이브러리 삭제 후 framer motion으로 변경
- @jpark0506 준혁님께서 만들어두신 navigationResult.tsx의 bottomSheet를 활용하였습니다.
```typescript
<AnimatedContainer
isVisible={isDetailView}
className="absolute bottom-0 w-full left-0 bg-white rounded-t-2xl shadow-xl overflow-auto"
positionDelta={MAX_SHEET_HEIGHT}
transition={{ type: "spring", damping: 20, duration: 0.3 }}
motionProps={{
drag: "y",
dragControls,
dragListener: false,
dragConstraints: {
top: 0,
bottom: MIN_SHEET_HEIGHT,
},
onDrag: handleDrag,
onDragEnd: handleDrag,
}}
>
<BottomSheetHandle dragControls={dragControls} />
<div
ref={scrollRef}
className="w-full overflow-y-auto"
style={{
height: MAX_SHEET_HEIGHT - BOTTOM_SHEET_HANDLE_HEIGHT,
}}
onScroll={preventScroll}
>
<NavigationDescription isDetailView={true} …
```
> [UNI-208] refactor : 지도 메인 페이지 바텀 시트 react-spring-bottom-sheet 라이브러리 제거

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/logging/ArgType.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/logging/ExecutionLoggingAop.java
- 로그 메세지의 가독성 및 정보량에 아쉬움이 있어 개선해봤습니다.
- DTO 또는 엔티티의 경우에도 재귀적으로 모든 데이터를 출력하도록 수정했습니다.
- depth 를 두어, 보다 더 쉽게 로그 값을 확인할 수 있도록 개선했습니다.
- 이로 인해 로그메세지가 오히려 길어져서 가독성을 헤칠 수도 있을 것 같은데요! 만약 그렇게 된다면 다시 롤백해보도록 하겠습니다!
- feat/
> [UNI-139] refactor: 로깅 메세지 가독성 좋게 변경

- uniro_backend/build.gradle
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/controller/AuthApi.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/controller/AuthController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/dto/request/LoginReqDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/dto/response/LoginResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/entity/Admin.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/interceptor/AdminInterceptor.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/interceptor/JwtInterceptor.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/jwt/JwtTokenProvider.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/jwt/SecurityContext.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/repository/AdminRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AuthService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/WebMvcConfig.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
- uniro_backend/src/main/resources/application-dev.yml
- uniro_backend/src/main/resources/application-local.yml
- uniro_backend/src/main/resources/application-test.yml
- 로그인 기능을 구현했습니다. code와 univId 를 입력하면 액세스 토큰을 발행하는 로직입니다.
- admin 엔티티 정의도 같이 봐주시면 감사하겠습니다 !
- 기존에는 필터를 통해 구현하려고 했으나 스프링 시큐리티를 사용하지 않고 빠르게 구현하기 조금 어렵다고 판단했습니다.
- 따라서 인터셉터로 구현하여 컨트롤러 단 전에서 필터링 하도록 구현했습니다.
- 어드민 인증은 되었지만, 특정 대학교가 아닌 다른 대학교의 접근은 금지하는 것이 필요했습니다.
- 처음에는 서비스 로직에 if 문으로 뺄려고 했습니다.
- 하지만 중복된 코드가 많고, 실제 서비스 로직과 관심사가 다르다고 생각하여 인터셉터로 분리하였습니다.
- 이에 대해 의견 있으시면 편하게 말씀주세요 !!
<br>
- **해당 세팅은 WebMvcConfig 를 통해서도 확인 가능합니다.**
- feat/
> [UNI-219] feat: 로그인 기능 구현 및 JWT 인터셉터 구현

- uniro_frontend/src/components/map/TopSheet.tsx
- uniro_frontend/src/components/map/mapBottomSheet.tsx
- uniro_frontend/src/components/map/mapSearchInput.tsx
- uniro_frontend/src/hooks/useSearchBuilding.ts
- uniro_frontend/src/pages/buildingSearch.tsx
- uniro_frontend/src/pages/demo.tsx
- uniro_frontend/src/pages/map.tsx
1.  지도 메인페이지 UX / UI 개선
2. TopSheet, BottomSheet 재설정
3. 시작 도착 선택시 해당 마커를 보일 수 있도록 지도 이동
4. 지도 검색 페이지, 뒤로가기 버튼 추가
```typescript
<MapTopBuildingSheet isVisible={(selectedMarker?.type === Markers.BUILDING ? false : true) && searchMode === "BUILDING"} />
<MapTopRouteSheet isVisible={(selectedMarker?.type === Markers.BUILDING ? false : true) && searchMode != "BUILDING"} />
<div ref={mapRef} className="w-full h-full" />
<MapBottomSheet
selectRoutePoint={selectRoutePoint}
selectedMarker={selectedMarker}
isVisible={selectedMarker?.type === Markers.BUILDING ? true : false}
/>
```
- 시트를 보여주는 시나리오는 총 3가지가 존재합니다.
- 1. 건물을 선택하여 BottomSheet 보여주기
- 2. 건물을 검색하기 위한 건물 검색 TopSheet 보여주기
- 3. 경로를 검색하기 위한 경로 검색 TopSheet 보여주기
- 2번과 3번을 구분하기 위해, 기존에 있던 useSearchBuilding에서 2가지 모드를 3가지 `BUILDING, ORIGIN, …
> [UNI-221] feat : 지도 메인페이지 UX 개선 및 길찾기 사용자 로직 변경

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
- uniro_backend/src/test/java/com/softeer5/uniro_backend/map/service/MapServiceTest.java
- 근접(2 노드 미만)한 노드에서 동일한 좌표값의 노드가 들어올 경우 예외가 발생하도록 구현했습니다.
- 첫번째 요소도 검사를 해야했기에 for문을 2개 만들어야 하는 아쉬움이 있었습니다.
- 이를 개선하기 위해 코드의 가독성을 위해 원래 N번 순회하던 것을 2N 순회로 변경하였습니다.
- 성능적으로는 아쉬울 수 있지만 가독성이 높아졌고, N^2이 아닌 2N이라 괜찮다고 생각했는데 의견 궁금합니다!
- feat/
> [UNI-217] fix: 길 추가시 동일한 노드 판단 로직 구현

- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/building/entity/Building.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/building/repository/BuildingRepository.java
- 건물노드를 _aud 테이블에서 특별히 관리하진 않기로 했습니다.
- 하지만 롤백 기능 사용시, building 테이블에는 존재하지만, node 테이블에는 존재하지 않은 데이터가 발생할 여지가 있다고 생각했습니다.
- 이에 해당 문제를 해결하기 위해 특정 시점으로부터 만들어진 노드뿐만 아니라 building 도 삭제하도록 구현했습니다.
- feat/
> [UNI-213] feat: 롤백 기능시 건물노드 삭제 기능 포함

- uniro_backend/src/main/java/com/softeer5/uniro_backend/building/controller/BuildingApi.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/building/controller/BuildingController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/building/dto/response/SearchBuildingResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/building/repository/BuildingCustomRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/building/repository/BuildingCustomRepositoryImpl.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/building/service/BuildingService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/controller/UnivApi.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/controller/UnivController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/dto/SearchUnivResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivCustomRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivCustomRepositoryImpl.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/service/UnivService.java
- 대학교 및 건물 이름 순으로 조회하도록 수정했습니다.
- 페이지네이션 삭제에 대해서는 논의 후에 적용하겠습니다.
- feat/
> [UNI-237] fix: 대학교 및 건물 이름 순으로 조회하도록 수정 맟 페이지네이션 삭제

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/constant/UniroConst.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
- uniro_backend/src/test/java/com/softeer5/uniro_backend/fixture/NodeFixture.java
- uniro_backend/src/test/java/com/softeer5/uniro_backend/map/service/RouteCalculatorTest.java
- 휴리스틱 # 1 : 출발점, 도착점의 해발고도가 각각 15m, 20m일때, 지나가는 길의 해발고도가 이 15~20m 범위를 벗어나는 경우 가중치 부여 (for 휠체어)
- 가중치 부여 정도 : (((벗어난 해발고도 차이)^2) / 10 ) * 해당 길의 거리
- ex1. 해발고도가 20m->21m인 곳을 10m 진행 시 10+1^2 m를 진행한 것으로 간주
- ex2. 해발고도가 22m->23m인 곳을 10m 진행 시 10+3^2 m를 진행한 것으로 간주
- 휴리스틱 # 2 : 지나온 주의요소의 길의 개수에 따른 가중치 부여 (only for 휠체어 빠른길)
- 가중치 부여 정도 : (지나온 주의요소의 개수)^2
- ex1. 지금까지 지나온 주의요소가 2개이고, 다음 진행할 3m짜리 길에 주의요소가 있다면 3+3^2 m를 진행한 것으로 간주
- 두 가지 휴리스틱이 잘 반영되는지 테스트 코드를 통해 확인하였습니다.
휴리스틱을 텍스트로 가독성있게 작성하기 어려워서 추후 오프라인으로 그림을 통해 이야기 나눠보면 좋을 것 같습니다!
> [UNI-232] 길 찾기 알고리즘 마이그레이션 (다익스트라 -> A*)

- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/dto/response/ChangedRouteDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/repository/RouteAuditRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/setting/RevisionContext.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/controller/MapApi.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/controller/MapController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/GetChangedRoutesByRevisionResDTO.java
- uniro_backend/src/test/java/com/softeer5/uniro_backend/admin/AdminServiceTest.java
- uniro_backend/src/test/resources/sql/delete-all-data.sql
- 현재 저희 서비스에서 지도를 불러오는 로직은 무거운 로직입니다. 이로 인하여 매번 지도를 불러올 경우 사용자 경험에 영향을 주었고, 이를 해결하고자 하였습니다.
- 우선 클라이언트 단에서 캐시되어있는 지도 데이터를 사용자에게 제공하여 First Contentful Paint (첫 컨텐츠 렌더링 시점)를 단축시켰습니다.
- 이후 별도의 API호출을 통해 변경사항들을 후처리함으로써 데이터의 최신성을 보장할 수 있게 되었습니다.
- https://github.com/softeer5th/Team2-Getit/pull/124 의 API를 응용하여 특정 버전과 현재 버전의 차이점을 조회할 수 있도록 구현하였습니다.
- @mikekks 님의 코드리뷰를 반영하여 해당 시점 이후의 변경사항들만 조회하여 더욱 응답시간을 단축시킬 수 있었습니다.
- 테스트코드를 확인해보시면 좋을 것 같습니다
> [UNI-238] feat : 현재 버전과 특정 버전의 차이점 조회 API 구현

- uniro_frontend/src/component/NavgationMap.tsx
- uniro_frontend/src/components/navigation/bottomSheet/bottomSheetHandle.tsx
- uniro_frontend/src/components/navigation/card/bottomCardList.tsx
- uniro_frontend/src/components/navigation/navigationDescription.tsx
- uniro_frontend/src/components/navigation/route/routeCard.tsx
- uniro_frontend/src/components/navigation/route/routeList.tsx
- uniro_frontend/src/hooks/useNavigationBottomSheet.tsx
- uniro_frontend/src/pages/navigationResult.tsx
1. 길찾기 바텀시트 번호 클릭시 이동
2. 바텀시트의 스크롤 범위와 올릴 수 있는 범위를 수정
번호 이동은 index로 관리했으며, route의 index로 관리했습니다.
```typescript
const [currentRouteIdx, setCurrentRouteIdx] = useState(-1);
```
index를 설정하는 함수와 reset하는 함수를 활용해, 필요한 곳마다 로직을 부여했습니다.
```typescript
const resetCurrentIndex = () => {
setCurrentRouteIdx(-1);
};
const changeCurrentIndex = (index: number) => {
setCurrentRouteIdx(index);
};
```
Navigation Map에서는, 
```typescript
const saveAllBounds = () => {
if (!map || !compositeRoutes) return;
const bounds = new google.maps.LatLngBounds();
Object.values(compositeRoutes).forEach((composite) => {
bounds.extend(composite!.bounds.getNorthEast());
bounds.extend(composite!.bounds.getSouthWest());
});
boundsRef.current = bounds;
};
```
bounds를 원래대로 되돌리는 함수를 제작하고,
```typescript
useEffect(() => {
if …
```
> [UNI-250] feat : 길찾기 바텀시트 번호 클릭시 이동 (hotfix 포함)

- uniro_frontend/src/component/NavgationMap.tsx
- uniro_frontend/src/components/map/mapMarkers.tsx
- uniro_frontend/src/utils/markers/createRiskMarker.ts
1. 위험 마커 축소, 위험 마커 Animation 및 마커 설명 삽입
네비게이션 페이지에서 사용하는 마커는 일반 마커와 다른 특성을 가지고 있습니다.
- 작은 상태에서 커져야 한다는 점
- 커질 때, 자연스럽게 어떤 위험 요소인지 보여야 한다는 점
때문에 기존 createElementMarker를 사용하기 어렵다고 느꼈고, 직접 DOM을 조작하는 방법을 연구해 따로 함수로 분리했습니다.
```typescript
export const createRiskMarkers = (
riskData: DangerRoute[],
map: google.maps.Map,
AdvancedMarker: typeof google.maps.marker.AdvancedMarkerElement,
): AdvancedMarker[] => {
const markers: AdvancedMarker[] = [];
riskData.forEach((route) => {
const markerElement = createMarkerElement({
type: Markers.DANGER,
className: "translate-pinmarker",
hasAnimation: true,
});
const marker = createAdvancedMarker(
AdvancedMarker,
map,
centerCoordinate(route.node1, route.node2),
markerElement,
);
const markerEl = marker.content as HTMLElement;
const innerEl = …
```
> [UNI-254] feat : 위험 마커 축소, 위험 마커 Animation 및 마커 설명 삽입

- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/dto/response/GetAllRoutesByRevisionResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/repository/RevInfoRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/controller/MapApi.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/controller/MapController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/AllRoutesInfo.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/GetAllRoutesResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/GetChangedRoutesByRevisionResDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
- uniro_backend/src/test/java/com/softeer5/uniro_backend/admin/AdminServiceTest.java
- 버전 id 데이터를 줘야하는 요구사항을 위해 구현했습니다.
- Calculator 로직은 변동하지 않았고, Calculator 반환값과 MapController의 반환값이 같았는데 이를 분리했습니다.
- Calculator 반환 DTO의 네이밍이 기존에는 ~~ResDTO 였지만 이제 이를 그대로 반환하지 않기 때문에 이름을 수정했습니다.
- feat/
> [UNI-249] feat: 현재 버전에 대한 버전 반환 기능 구현

- .github/workflows/fe-admin-deploy.yml
- .github/workflows/fe-deploy.yml
기존에는 admin PR, fe PR이 구분이 불가능해 fe-workflow와 fe-admin-workflow가 두번 돌아가며 ngnix가 바라보는 docker container가 꼬이는 현상이 발생했습니다.
해결책을 찾던 중, workflow의 path 조건을 배우게 되어, 폴더별로 실행이 가능하게 변경하였습니다.
감사합니다.
테스트 없음.
fe
> [UNI-224] 배포(www<->admin) 주소 바뀌는 현상 fix

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/CorsConfig.java
CORS config의 allowedHeaders에 Authorization를 명시하여 preflight 관련 문제를 해결하였습니다.
> [UNI-260] fix : CORS allowedHeaders에 Authorization 명시

- uniro_frontend/src/component/NavgationMap.tsx
- uniro_frontend/src/components/navigation/route/routeList.tsx
- uniro_frontend/src/pages/navigationResult.tsx
```typescript
// Caution 마커를 위한 routeIdx state
const [cautionRouteIdx, setCautionRouteIdx] = useState(-1);
```
본래 ref를 이동시키는 함수를, useRef로 RouteCard를 이동하고, fowardRef로 부모에게 ref와 useImperativeValue로 ref를 transform하는 함수를 부모에게 넘겨주어, Navigation Map event를 걸어주려고 했었습니다.
하지만 ref가 바텀시트가 올라오지 않으면, useImperativeValue에서 cardRef가 존재하지 않아 cardRef를 transform하는 함수가 undefined가 되어, 함수 호출이 안되는 문제가 발생하였습니다.
그래서 추가적인 state로 관리하고, cautionRouteIdx로 기존 routeIdx로 이동하는 방식과 동일한 방식으로 구현했습니다.
https://github.com/user-attachments/assets/5cfcb8ec-57d0-4c7e-a1bd-40553d1a823c
fe
> [UNI-256] feat : 길찾기 페이지 주의 요소 클릭 시 지도 및 바텀 시트 이동

- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/repository/NodeAuditRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/repository/RouteAuditRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/entity/Route.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/repository/NodeRepository.java
- forEntitiesAtRevision을 사용했을 때, N+1 문제가 발생하여 forRevisionsOfEntity로 쿼리문을 변경하였습니다.
- forRevisionsOfEntity에서 조회한 route는 node가 fetch되어있지 않기 떄문에 매핑해주는 코드를 추가하였습니다.
> [UNI-264] refactor : aud 테이블에서 조회하던 쿼리문 최적화

- uniro_admin_frontend/src/AppRouter.tsx
- uniro_frontend/src/App.tsx
- react-query client stale Time 5분 설정
- 기존에 클라이언트에서 작은 데이터 통신과정에서 캐시 stale 타임을 설정하지 않았는데, revision 비교 API가 서버에 많은 부담이 되어 캐시를 위해 stale 타임을 추가합니다.
> [UNI-277] hotfix : QueryClient Stale default 값 설정

- uniro_frontend/src/component/NavgationMap.tsx
- uniro_frontend/src/data/types/marker.d.ts
- uniro_frontend/src/index.css
- uniro_frontend/src/pages/map.tsx
- uniro_frontend/src/pages/reportRisk.tsx
- uniro_frontend/src/pages/reportRoute.tsx
- uniro_frontend/src/utils/markers/createMarkerElement.ts
- uniro_frontend/src/utils/markers/createRiskMarker.ts
- #18 에서 생성한 `createMarkerElement` 함수를 리팩토링 하였습니다.
```typescript
createMarkerElement({
type: Markers.ORIGIN,
title: marker.property.buildingName,
className: "translate-pinmarker",
});
```
- 기존 하나의 함수, `createMarkerElement`에 마커의 타입, 이름 등 정보를 입력하여 다양한 종류의 마커를 생성하던 과정을 각 종류별 마커를 생성하는 독립 함수로 분리하였습니다
```typescript
const {
cautionMarkerElement,
dangerMarkerElement,
buildingMarkerElement,
selectedBuildingMarkerElement,
originMarkerElement,
destinationMarkerElement,
} = createMarkerElement();
originMarker.content = originMarkerElement({ name: origin.buildingName });
```
- 다음과 같이 분리하여 더 명확한 기능을 수행하는 함수로 분리하였습니다.
- 내부 함수들은 Closure로 안에서만 접근이 가능합니다.
- 다음과 같이 그림자가 있는 마커는 `translate-shadowmarker`
- 다음과 같이 아래 이름이 있는 마커는 `translate-namedmarker` 로 변경하였습니다.
- 현재와 동일 결과 확인하였습니다.
- PR이 승인되면 추후 Navigation등 현재 …
> [UNI-267] refactor : createMarkerElement 재 함수화 및 적용

- uniro_frontend/src/components/customInput.tsx
- uniro_frontend/src/pages/buildingSearch.tsx
Input 컴포넌트와 검색 페이지의 flexbox 레이아웃 호환성을 개선했습니다.
```typescript
- className={h-[60px] w-full max-w-[450px] px-[14px] flex flex-row ...}
+ className={h-[60px] flex-1 min-w-0 flex flex-row max-w-[450px] px-[14px] ...}
```
```typescript
- className="h-full flex-1 mx-[14px] ..."
+ className="h-full flex-1 min-w-0 mx-[14px] ... appearance-none"
```
Safari의 WebKit 엔진은 flexbox 명세를 엄격하게 해석하여, min-width: auto(기본값)일 때 컨텐츠 크기 이하로 축소되지 않는 문제가 있습니다. 이로 인해 flex 레이아웃이 의도한 대로 동작하지 않았습니다.
다음은 각 엔진을 비교한 표인데, Webkit이 상대적으로 flex에 대해 엄격하다는 것을 알 수 있고, min-content를 명시해주지 않는 이상, w-full을 그대로(부모에 꽉차게) 사용하려고 한다는 것을 알 수 있습니다. 그래서 음성인식 버튼이나, 닫는 버튼이 옆으로 밀려난 것을 볼 수 있습니다.
WebKit | 컨텐츠 기반 강제 적용 | min-content 이상
Blink | 컨테이너 공간 우선 | 0까지 허용
Gecko | 유연한 가변 처리 | 상황에 따라 조정
iOS Safari나 macOS Safari 브라우저의 입력 요소는 각 브라우저의 CSS처럼 기본 …
> [UNI-279] fix : IOS Safari Browser 레이아웃 깨짐 해결

- uniro_frontend/src/components/loading/loading.tsx
- uniro_frontend/src/hooks/useUniversityInfo.tsx
- uniro_frontend/src/pages/landing.tsx
- uniro_frontend/src/pages/map.tsx
- uniro_frontend/src/pages/navigationResult.tsx
- uniro_frontend/src/pages/universitySearch.tsx
1. 주의요소 위험요소 마커 클릭시 한양대학교로 이동하는 현상 수정
2. Landing 페이지, 학교 선택 페이지에서 Persist 지우기
3. 학교 없이 로딩 화면 조회 시 학교 제거 및 Default 메세지 설정하기
4. origin, destination 없을 때 메인 화면으로 돌아가지 않는 문제 해결
5. 지도 메인 페이지 center point 수정
이슈 별로 1~2줄 수정했기 때문에, 커밋별로 봐주시면 감사하겠습니다.
https://github.com/user-attachments/assets/45049d2d-54aa-48a0-8c69-3f246bbdd934
https://github.com/user-attachments/assets/a80ddff6-15b4-474a-af07-1992cfda9062
-> 보여지는 화면은 없지만, 혹시 모를 상황을 대비해서 만들어놓았습니다.
https://github.com/user-attachments/assets/331d6246-37fc-4f96-b8a3-2b3fbe329a3f
https://github.com/user-attachments/assets/217c15a8-8739-4753-915f-434be56b6bfe
fe
UNI-291, UNI-292,UNI-293,UNI-295
> [UNI-290] 각 페이지 별 방어 코드 및 버그 수정

- uniro_frontend/src/App.tsx
- uniro_frontend/src/components/error/NotFound.tsx
- uniro_frontend/src/pages/notFound.tsx
접근할 수 없는 경로에 피드백이 필요할 것으로 보여, 404 페이지를 추가하고, 오류가 발생했을때도 돌아갈 수 있도록 하였습니다.
```typescript
const handleGoBack = () => {
if (window.history.length > 1) {
navigate(-1);
} else {
navigate("/");
}
};
```
동현님 말대로, 사용자가 뒤로가기를 제스처로 고려하는 경우도 있고, 오류가 발생해도 바로 뒤로 가는 것이 자연스럽다고 느껴져 해당 로직을 반영했습니다.
다만, 사용자가 변형된 링크(카카오톡 공유 etc..)로 바로 접속했을 경우도 대비를 해야하기 때문에, history 객체를 사용해 구분했습니다.
버튼 children에도 차이점을 뒀습니다.
```typescript
<div onClick={handleGoBack} className="absolute bottom-6 space-y-2 w-full px-4">
<Button variant="primary">{window.history.length > 1 ? "뒤로 가기" : "홈으로 이동"}</Button>
</div>
```
감사합니다.
https://github.com/user-attachments/assets/36d81634-258d-4092-bda3-7db81d7bcb11
https://github.com/user-attachments/assets/47eb1543-ef5e-41f3-8c0f-4a974e82a655
fe
UNI-298, UNI-299
> [UNI-296] feat : 404 페이지 제작 및 오류 발생 시 돌아가는 버튼 추가

- uniro_frontend/src/components/universityButton.tsx
- uniro_frontend/src/pages/landing.tsx
- uniro_frontend/src/pages/universitySearch.tsx
1. 랜딩 페이지 클릭 시 이동
div 전체에 이동을 걸어놓았습니다.
3. 랜딩 페이지 텍스트 애니메이션
```typescript
<motion.p
initial={{ opacity: 0, y: 50 }}
animate={{ opacity: 1, y: 0 }}
transition={{ duration: 0.5, delay: 0.3, ease: "easeInOut" }}
className="text-kor-heading1 font-bold"
>
어디든 갈 수 있는 캠퍼스.
</motion.p>
<motion.p
initial={{ opacity: 0, y: 50 }}
animate={{ opacity: 1, y: 0 }}
transition={{ duration: 0.5, delay: 0.8, ease: "easeInOut" }}
className="text-kor-heading1 font-bold"
>
쉽고 빠르게 이동하세요.
</motion.p>
```
motion.p를 사용해, 각각 애니메이션이 올라오도록 했습니다.
5. 학교 더블 클릭시 선택
```typescript
onClick={() => {
if (selectedUniv?.id === univ.id) {
setUniversity(univ);
navigation("/map");
return;
}
setSelectedUniv(univ);
}}
```
onClick코드를 수정했습니다.
7. 학교 배경 클릭 시 선택 해제
```typescript
<div className="h-full w-full" onClick={() => …
```
> [UNI-305] feat : 랜딩페이지, 학교 검색 관련 기능 추가

- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
- createValidRouteNodes 에서 buildingNode일 시 nodeMap과 strTree에 포함되지 않도록 변경하였습니다.
> [UNI-316] refactor : 빌딩과 연결된 간선은 길 추가 시 크로스체크 하지 않도록 변경

- uniro_frontend/src/hooks/useMap.tsx
- uniro_frontend/src/map/initializer/googleMapInitializer.ts
- uniro_frontend/src/map/loader/googleMapLoader.ts
- uniro_frontend/src/pages/map.tsx
- uniro_frontend/src/pages/reportForm.tsx
- uniro_frontend/src/pages/reportRisk.tsx
- uniro_frontend/src/pages/reportRoute.tsx
```typescript
const drawPolygon = () => {
if (!Polygon) return;
const polygonPath = university.areaPolygon;
const areaPolygon = new Polygon({
map: map,
paths: polygonPath,
fillColor: "#ff2d55",
fillOpacity: 0.1,
strokeColor: "#ff2d55",
strokeOpacity: 0.5,
});
polygon.current = areaPolygon;
};
```
- 대학 리스트 조회 시, 받게되는 areaPolygon 값으로 전체 Polygon을 생성합니다.
- 색상은 임의로 빨간색으로 변경하였습니다.
- 추후 길 색상과 함께 변경할 수 있습니다.
- drawRoute 같은 공통 함수를 분리할 예정입니다.
https://github.com/user-attachments/assets/48c979ae-0045-4f05-a1f3-8fda0f0f1e53
UNI-317
>  [UNI-307] feat : 지도 메인 페이지 경로 노출 적용 및 길 색상 변경 및 학교 영역 폴리곤 생성

- uniro_backend/src/main/java/com/softeer5/uniro_backend/UniroBackendApplication.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/AsyncConfig.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/constant/UniroConst.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/controller/MapApi.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/controller/MapController.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/repository/RouteRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
- 기존에는 List<Route>로 전체 데이터를 한 번에 조회하다 보니, 한정된 EC2 인스턴스 리소스 환경에서 수만 개의 Node와 Route 데이터를 여러 쓰레드가 동시에 조회할 때 OOM(OutOfMemory) 문제가 발생했습니다.
- 이를 해결하기 위해, 전체 데이터를 한꺼번에 메모리에 적재하는 대신, Stream<Route>를 활용하여 일정 단위(예: 2500건)로 데이터를 처리하도록 변경했습니다.
- 각 배치 처리 후 entityManager.detach()와 리스트 클리어 작업을 통해 영속성 컨텍스트 및 메모리에서 불필요한 데이터를 제거하여, GC가 효과적으로 메모리를 회수할 수 있도록 구현하였습니다.
- 전체 데이터를 한 번의 응답으로 전달하면 응답 데이터가 누적되어 메모리 사용량이 급증할 수 있는 문제가 있었습니다.
- 이를 개선하기 위해, Server-Sent Events(SSE)를 도입하여 데이터를 배치 단위로 분할하여 전송하도록 변경하였습니다.
- 이 방식은 클라이언트가 각 배치 데이터를 즉시 처리할 수 있게 하여, 서버 측에서는 응답 데이터를 누적하지 않고 지속적으로 메모리를 해제할 수 있도록 합니다.
- 또한, Stream과 SSE 기법을 결합하여 메모리 부담을 최소화하면서 응답 속도와 처리 효율을 극대화하였습니다.
조건 : 힙 메모리 500MB, 쓰레드 15개, 루프카운트 10
[UNI-324]: https://uniro.atlassian.net/browse/UNI-324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
> [UNI-323] feat : Stream + SSE로 대용량 조회 분할처리 로직 구현

- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
- 기존 길 찾기 상세경로에서 좌회전,우회전 판단은 코어노드로부터 전,후 노드였습니다.
- 이 경우 일부 경로에서 직진임에도 좌,우회전으로 판단되는 경우가 있어 로직을 수정하였습니다.
- 상세경로에서 좌,우회전 판단할 때 코어노드로부터 이전2번째 노드, 이후2번째 노드로 판단하도록 변경하였습니다.
> [UNI-218] refactor : 길 찾기 상세경로 좌회전,우회전 로직 수정

- uniro_frontend/src/components/report/reportTitle.tsx
- uniro_frontend/src/hooks/useReportRiskResult.tsx
- uniro_frontend/src/pages/map.tsx
- uniro_frontend/src/pages/reportForm.tsx
- uniro_frontend/src/pages/reportRisk.tsx
```typescript
import { create } from "zustand";
import { RouteId } from "../data/types/route";
import { CautionFactor, DangerFactor } from "../data/types/factor";
interface ReportedRiskResult {
reportedData: {
universityId: number | undefined;
routeId: RouteId | undefined;
cautionFactors: CautionFactor[];
dangerFactors: DangerFactor[];
};
setReportedRouteData: (params: {
universityId: number;
routeId: RouteId;
cautionFactors: CautionFactor[];
dangerFactors: DangerFactor[];
}) => void;
clearReportedRouteData: () => void;
}
const useReportedRisk = create<ReportedRiskResult>((set) => ({
reportedData: {
universityId: undefined,
routeId: undefined,
reportedCoord: undefined,
cautionFactors: [],
dangerFactors: [],
},
setReportedRouteData: ({
universityId,
routeId,
cautionFactors,
dangerFactors, …
```
> [UNI-336] 제보하기 페이지 등록 이후 위치 이동 구현, 제보 취소, 제보 후 캐시 수정 구현

- uniro_frontend/src/pages/reportRisk.tsx
```typescript
if (reportedData?.routeId !== undefined) {
// 기존 코드와 동일
if (map) {
if (reportedData?.routeId !== undefined) moveToMarker();
```
routeId를 체크해 확실하게 다른 학교로 넘어가는 것을 방지했습니다.
빠른 발견 감사합니다.
https://github.com/user-attachments/assets/cf5fa424-002f-4d14-a5c3-87a9fb3c882a
fe
> [UNI-342] fix : 다른 학교로 이동하는 현상 해결

- .github/workflows/fe-deploy.yml
- uniro_frontend/src/App.tsx
```typescript
const BuildingSearchPage = lazy(() => import("./pages/buildingSearch"));
const MapPage = lazy(() => import("./pages/map"));
const ReportForm = lazy(() => import("./pages/reportForm"));
const NavigationResultPage = lazy(() => import("./pages/navigationResult"));
const ReportRoutePage = lazy(() => import("./pages/reportRoute"));
const ReportRiskPage = lazy(() => import("./pages/reportRisk"));
```
- 랜딩 페이지
- 대학 검색 페이지(테스트 결과 중간 로딩화면 깜빡임 발생하는 유일한 페이지)
- 에러페이지
- Not Found 페이지
- Offline 페이지
- ErrorTest 페이지
번들이이 Lazy Loading에 맞게 잘 분할된 것을 볼 수 있습니다. Loading이 길어질 것으로 예상되는 Component에서 1자리 kb js를 다운로드 하기 때문에, 거의 영향이 없을 것으로 예상됩니다.
코드 결합 후 FCP랑 LightHouse 측정하면 유의미한 결과가 있을 것 같습니다.
감사합니다.
fe
> [UNI-313] feat : 초기 로딩시 필요없는 화면에 대해 Lazy Loading 적용

- uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/building/service/BuildingService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/RedisConfig.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/WebMvcConfig.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/external/elevation/MapClient.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/external/elevation/MapClientImpl.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/external/redis/RedisService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/repository/RouteRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/vo/LightRoute.java
- uniro_backend/src/test/java/com/softeer5/uniro_backend/external/MapClientImplTest.java
- uniro_backend/src/test/java/com/softeer5/uniro_backend/map/service/MapServiceTest.java
- 기존에 부하테스트를 진행하다 힙 사용량이 높아 OOM 문제가 발생하는 것을 확인했습니다.
- 이를 개선하기 위해 redis 캐시를 사용할 때도 배치단위로 스트림 읽도록 구현하여 총 메모리 사용량을 줄였습니다.
- 길 추가 로직이나 롤백 로직에서는 해당 캐시 정보가 지워지도록 구현했습니다.
- DB에서 객체를 가져올 때 너무 무거워 메모리 사용량이 높다는 문제점이 있었습니다.
- 이를 해결하기 위해 프로젝션을 활용하여 필요한 데이터만 가져오도록 구현했습니다.
- feat/
> [UNI-255-v4] refactor: 스트림 기반 redis 구현 및 경량객체 조회하도록 개선 (UNI-321)

- uniro_frontend/src/components/navigation/route/routeList.tsx
```typescript
return (
<div className="w-full scroll-x-hidden">
```
RouteList에 스크롤 제한을 걸어주었습니다.
감사합니다.
https://github.com/user-attachments/assets/03f906cc-74b7-4cf6-839f-7038104a4943
https://github.com/user-attachments/assets/2dc803dd-9e5e-4be1-92ca-ecab6f20c060
fe
> [FE-356] fix : 길 찾기 페이지 바텀시트 스크롤 x 차단

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/SchedulerConfig.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/logging/ExecutionLoggingAop.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/external/MapClientImpl.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/external/event/RouteCreatedEvent.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/external/event/RouteEventListener.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/external/event/RouteEventService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/entity/Node.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/enums/HeightStatus.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/repository/NodeRepository.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
- uniro_backend/src/test/java/com/softeer5/uniro_backend/fixture/NodeFixture.java
- 구글 API를 길 추가 요청 시 동기적으로 호출하지 않고, 이벤트 기반으로 처리하도록 변경했습니다.
- 이를 통해 API 호출로 인한 응답 지연 및 비용 부담을 줄이고, 사용자 경험을 개선했습니다.
- 구글 API는 한 번의 요청으로 최대 512개의 점에 대한 해발고도를 제공하며, 호출당 비용이 발생합니다.
- 비용 절감을 위해, 첫 유저가 길 추가 요청을 시작하면 30분 동안 다른 유저들의 요청을 모은 후 배치로 처리하도록 구현했습니다.
- **구현 내용:**
- 요청된 노드 데이터를 배치 단위(최대 300개 단위)로 분할하여 처리하도록 로직을 작성했습니다.
- Spring WebClient와 Reactor를 활용해 Google Elevation API를 비동기 방식으로 호출, 각 배치를 병렬로 처리합니다.
- 모든 배치 요청이 완료될 때까지 비동기 작업을 모니터링하며, 응답 결과를 매핑하여 노드에 해발고도를 적용합니다.
- 이벤트 기반 스케줄러를 통해 30분 간격으로 모인 요청들을 한 번에 처리하도록 하여, 호출 횟수를 줄이고 비용을 최적화했습니다.
> [UNI-354] feat : 이벤트를 통한 Google API호출 + 배치로 처리하는 로직 작성

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/constant/UniroConst.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/FastestRouteDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/FastestRouteResultDTO.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
- uniro_backend/src/test/java/com/softeer5/uniro_backend/map/service/RouteCalculatorTest.java
1. 길 찾기 로직은 cost (소요시간) 산정 시 distance에 일정 상수를 곱하여 산정하였습니다.
- 이는 실제 소요시간과 차이가 있을 것으로 생각되어 길 찾기 도중 사용하던 weight으로 산정하도록 변경하였습니다.
2. 길 찾기 로직은 기존 출발점과 도착점 해발고도 영역을 벗어날 때에만 해발고도를 고려하였습니다.
- 이 역시 실제 소요시간과 차이가 있을 것으로 생각되어, 모든 길의 해발고도 차이에 대해 연산하도록 구현하였습니다.
3. 위 두 가지 방식 변화로 인하여 소요시간이 급격히 증가하는 것을 방지하기 위해 상수(속력)를 수정하였습니다.
4. 잘못된 데이터로 인하여 너무 큰 영향을 끼치는 것을 방지하기 위해 LIMIT_RANGE 를 설정하였습니다.
- feat/
> [UNI-364] refactor : 길 찾기 로직에서 cost산정방식 변경 & 로직 수정

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/constant/UniroConst.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/external/elevation/MapClientImpl.java
- 변경 전 : 기존에는 WebClient 호출 스트림 체인에 subscribeOn(Schedulers.boundedElastic())만 사용하고 있었습니다.
- subscribeOn은 스트림 구독(데이터 요청)이 시작되는 업스트림 작업의 실행 스레드를 지정합니다. (우리 서비스에서는  fetchElevationAsync)
- 그러나 WebClient 호출은 기본적으로 논블로킹 I/O 작업이기 때문에, 블로킹 I/O나 시간이 오래 걸리는 작업에 최적화된 boundedElastic 스케줄러는 적합하지 않았습니다.
- 변경 후 : 스트림 체인에 subscribeOn(Schedulers.parallel())과 publishOn(Schedulers.parallel())를 모두 포함시켰습니다.
- publishOn은 이후의 후속 연산이 특정 스케줄러에서 수행되도록 강제합니다.
- WebClient 호출은 논블로킹 I/O 작업으로 parallel 스케줄러와 잘 맞으며, mapElevationToNodes는 단순 계산 및 데이터 할당 작업으로 CPU 집약적이고 빠르게 처리되는 작업이므로 parallel 스케줄러를 사용하는 것이 효율적입니다.
참고자료
- https://spring.io/blog/2019/12/13/flight-of-the-flux-3-hopping-threads-and-schedulers#are-schedulers-always-backed-by-an-executorservice
- https://stackoverflow.com/questions/61304762/difference-between-bounde …
> [UNI-340] refactor : Google API 비동기 처리 최적화 & Google API 호출 최대 개수 조정

- uniro_frontend/src/App.tsx
- uniro_frontend/src/pages/mapSSE.tsx
```typescript
useEffect(() => {
if (!map) return;
const eventSource = new EventSource(
`${import.meta.env.VITE_REACT_SERVER_BASE_URL}/${university.id}/routes/sse`,
);
eventSource.onmessage = (ev) => {
if (ev.isTrusted) {
const { batchSize, coreRoutes, nodeInfos }: GetAllRouteSSEResponse = JSON.parse(ev.data);
const routes = transformAllRoutes({ coreRoutes, nodeInfos });
drawRoute(routes);
sseCounter.current += 1;
if (sseCounter.current === 11) {
eventSource.close();
}
}
};
eventSource.onerror = (err) => {
console.log("ERROR");
};
return () => {
eventSource.close();
};
}, [map]);
```
- 현재 백엔드에서 배치 사이즈 등을 전달할 수 없다고 하여 하드코딩 해둔 상태입니다.
또한, 이전에는 모든 배치 데이터가 전달이 되었지만, 서버에서 문제가 발생하여 데이터가 정상적으로 수신되지 않습니다.
기존에 서버가 정상적으로 동작할때의 영상을 첨부합니다.
- 실제 딜레이를 주지 않을 경우, 기존 API와 비슷한 성능을 내고 있어서 첨부 영상에는 임의의 딜레이를 부여한 …
> [UNI-367] feat : 지도 메인페이지 SSE 이벤트 적용

- uniro_frontend/src/pages/navigationResult.tsx
```JSX
<div
onClick={routeList?.data[buttonState] ? showDetailView : () => {}}
aria-disabled={routeList?.data[buttonState] ? false : true}
className={`w-full h-15 ${routeList?.data[buttonState] ? "bg-primary-600 hover:bg-primary-700 active:bg-primary-700" : "bg-gray-500"} transition-color duration-200 flex flex-col items-center justify-center -mb-[30px] mt-4`}
>
<div className="text-white font-bold">상세경로 보기 </div>
</div>
```
routeList?.data[buttonState]로 현재 길 존재 여부를 판단해서 조건에 맞게 동작하도록 했습니다.
감사합니다.
https://github.com/user-attachments/assets/198f2061-70c7-4019-9758-2ad7bc4ac183
https://github.com/user-attachments/assets/93d9fc3b-ac97-4dcd-b6cb-884078b5c3c3
- fe
> [UNI-366] fix : 휠체어, 전동휠체어가 존재하지 않을 때 상세경로 보기 비활성화

- uniro_frontend/src/component/NavgationMap.tsx
- uniro_frontend/src/container/animatedContainer.tsx
- uniro_frontend/src/pages/navigationResult.tsx
```typescript
const raiseSheet = useCallback(() => {
new Promise<void>((resolve) => {
controls.start({ y: 0, transition: { duration: 0.5 } });
resolve();
}).then(() => {
setSheetHeight(MAX_SHEET_HEIGHT);
setTopBarHeight(PADDING_FOR_MAP_BOUNDARY);
});
}, [controls]);
const handleCautionMarkerClick = async (index: number, isDetailView: boolean) => {
if (isDetailView) {
await raiseSheet();
setTimeout(() => {
setCurrentRouteIdx(index);
setCautionRouteIdx(index);
}, 500);
return;
}
showDetailView();
setCurrentRouteIdx(index);
setTimeout(() => {
setCautionRouteIdx(index);
}, 800);
};
```
controls가 바뀌지 않으면 동일한 함수를 참조해야 해서(handleCautionMarkerClick이 자체 클로저를 가져 controls가 바뀌면 작동하지 않음) useCallback을 걸어주었습니다.
sheet를 올리는 과정을 await로 동기적으로 처리할 수 있도록 Promise를 구현했습니다.
감사합니다. …
> [UNI-369] fix : 바텀 시트 내린 상태에서 마커 클릭시 포지션이 밀리는 현상

- uniro_frontend/index.html
- uniro_frontend/src/components/building/buildingList.tsx
- uniro_frontend/src/components/building/buildingNotFound.tsx
- uniro_frontend/src/components/university/universityList.tsx
- uniro_frontend/src/components/university/universityNotFound.tsx
- uniro_frontend/src/components/universityButton.tsx
- uniro_frontend/src/pages/universitySearch.tsx
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
```
- 유저 피드백 과정에서 더블 터치로 인해 줌이 되는 것이 이상하다는 의견이 많이 나왔습니다.
- 메타 태그에 `user-scalable` 을 추가하였습니다.
```typescript
<div className="overflow-y-scroll flex-1">
<ul
className="w-full h-full px-[14px] py-[6px]"
onClick={() => {
setSelectedUniv(undefined);
}}
>
{universityList &&
universityList.map((univ) => (
<UniversityButton
key={`university-${univ.id}`}
selected={selectedUniv?.id === univ.id}
onClick={() => {
if (selectedUniv?.id === univ.id) {
setUniversity(univ);
navigation("/map");
return;
}
setSelectedUniv(univ);
}}
name={univ.name}
img={univ.imageUrl}
/>
))}
</ul>
</div>
```
onClick 이벤트로 더블 클릭을 관리하고 있던 것을 DoubleClick 이벤트로 분리하였습니다.
```typescript
<button
onDoubleClick={handleDbClick} …
```
> [UNI-370] feat : 검색 리스트 로딩 + NotFound 화면 적용

- uniro_frontend/src/pages/mapSSE.tsx
batchSize로 몇 번의 이벤트가 수신될 지를 받아서 종료 시점을 선택합니다.
| SSE | Non - SSE |
|----------|------------|
| <video src="https://github.com/user-attachments/assets/7df35f5d-81e2-4e71-96fc-2c21e3bc15d0"/> | <video src="https://github.com/user-attachments/assets/c5885d28-474a-4bb2-b4b5-1c29f1a886f8" />
- 초기 로딩 시간이 매우 빨라진 것을 확인할 수 있습니다.
- SSE 동작이 안정된다면 메인 페이지를 교체할 예정입니다.
> [UNI-367] fix : SSE 종료 시점 하드코딩 변수 제거

- uniro_frontend/src/components/navigation/route/routeCard.tsx
방향을 주는 카드들과 Danger, Caution 카드들이 CSS가 달라 Grid 형태로 같게 수정했습니다.
감사합니다.
fe
> [UNI-371] fix : 위험 주의 요소 바텀시트 레이아웃 이동 해결

- uniro_frontend/src/component/NavgationMap.tsx
- uniro_frontend/src/hooks/useNavigationBottomSheet.tsx
- uniro_frontend/src/pages/navigationResult.tsx
fitBounds의 디폴트 패딩을 window width의 10%로 수정했습니다.
길 상세보기 후 다시 돌아갈 시 bottom padding이 0으로 설정되어 있을 때가 있어서, 그런 부분들을 수정했습니다.
감사합니다!
https://github.com/user-attachments/assets/2844a8e1-b141-4f19-a366-9e1e7fff0c61
https://github.com/user-attachments/assets/e1611cee-4546-418d-94d8-a06234a4af67
fe
> [UNI-373] fix : 길찾기 화면의 과도한 패딩을, 핸드폰 뷰에 맞춰서 재수정

- uniro_backend/src/main/java/com/softeer5/uniro_backend/common/constant/UniroConst.java
- uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
> [UNI-53] fix : 새로운 길에 너무 많은 가중치를 부여하던 로직 변경
